"""
NEUM LEX COUNSEL — Rescue Service
app/services/rescue_service.py

Implements _save_rescue_plan, _get_rescue_plan_response,
_update_rescue_step, _create_engagement_from_rescue,
_create_tasks_from_rescue stubs.

The 8-step Corporate Rescue Sequence is generated by C_rule_engine.py
and persisted here. Step completion triggers compliance re-evaluation.
"""
from __future__ import annotations

import uuid
from datetime import UTC, date, datetime, timedelta

from sqlalchemy import select, update

from app.models.enums import (
    ComplexityLevel,
    EngagementStatus,
    RescueStepStatus,
    RevenueTier,
    TaskPriority,
    TaskStatus,
)
from app.models.rescue import RescuePlan, RescueStep
from app.services.base import BaseService


class RescueService(BaseService[RescuePlan]):
    model = RescuePlan

    # ── Rescue Plan ───────────────────────────────────────────────

    async def generate_rescue_plan(
        self,
        company_id: uuid.UUID,
        *,
        engine_output,          # EngineOutput from C_rule_engine.py
        assigned_staff_id: uuid.UUID | None = None,
        created_by: uuid.UUID | None = None,
    ) -> RescuePlan:
        """
        Persist the rescue plan generated by the rule engine.
        Deactivates any previous active plan before creating the new one.
        Creates RescueStep records for all 8 steps.
        Creates Tasks from rescue steps for staff assignment.
        Triggers Engagement creation in commercial service.
        """
        # Deactivate existing active plan
        await self.db.execute(
            update(RescuePlan)
            .where(
                RescuePlan.company_id == company_id,
                RescuePlan.is_active,
            )
            .values(is_active=False)
        )

        rescue_data = engine_output.rescue_plan
        if not rescue_data:
            raise ValueError("Engine output has no rescue plan — company may not be BLACK/RED.")

        revenue_tier = RevenueTier.CORPORATE_RESCUE
        score = engine_output.score_breakdown.final_score
        risk_band = engine_output.score_breakdown.risk_band

        plan = await self.create(
            company_id=company_id,
            plan_name=f"Corporate Rescue Plan — {date.today().strftime('%B %Y')}",
            revenue_tier=revenue_tier,
            initial_risk_band=risk_band,
            initial_score=score,
            years_in_default=getattr(rescue_data, "years_in_default", 0),
            is_active=True,
            started_at=datetime.now(UTC),
            total_steps=len(getattr(rescue_data, "steps", [])),
            completed_steps=0,
            blocked_steps=0,
            completion_percentage=0,
            assigned_staff_id=assigned_staff_id,
            created_by=created_by,
        )

        # Create step records
        steps = getattr(rescue_data, "steps", [])
        for step_data in steps:
            await self._create_step(plan.id, company_id, step_data)

        # Create tasks from steps
        await self._create_tasks_from_steps(plan.id, company_id, steps, assigned_staff_id)

        # Reload with steps
        await self.db.refresh(plan)
        return plan

    async def _create_step(
        self,
        plan_id: uuid.UUID,
        company_id: uuid.UUID,
        step_data,
    ) -> RescueStep:
        """Create a single rescue step record."""
        complexity_map = {
            "LOW": ComplexityLevel.LOW,
            "MEDIUM": ComplexityLevel.MEDIUM,
            "HIGH": ComplexityLevel.HIGH,
            "CRITICAL": ComplexityLevel.CRITICAL,
        }
        step = RescueStep(
            id=uuid.uuid4(),
            rescue_plan_id=plan_id,
            company_id=company_id,
            step_number=getattr(step_data, "step_number", 1),
            step_title=getattr(step_data, "title", f"Step {getattr(step_data, 'step_number', 1)}"),
            step_description=getattr(step_data, "description", ""),
            statutory_basis=getattr(step_data, "statutory_basis", None),
            complexity=complexity_map.get(
                getattr(step_data, "complexity", "MEDIUM"),
                ComplexityLevel.MEDIUM
            ),
            estimated_days_min=getattr(step_data, "days_min", 7),
            estimated_days_max=getattr(step_data, "days_max", 21),
            target_completion_date=date.today() + timedelta(
                days=getattr(step_data, "days_max", 21)
            ),
            step_status=RescueStepStatus.PENDING,
            triggers_reevaluation=getattr(step_data, "step_number", 0) == 8,
        )
        self.db.add(step)
        await self.db.flush()
        return step

    async def _create_tasks_from_steps(
        self,
        plan_id: uuid.UUID,
        company_id: uuid.UUID,
        steps,
        assigned_to: uuid.UUID | None = None,
    ) -> None:
        """
        Create staff task records from rescue steps.
        _create_tasks_from_rescue stub implementation.
        """
        from app.models.commercial import Task
        priority_map = {
            1: TaskPriority.CRITICAL, 2: TaskPriority.CRITICAL,
            3: TaskPriority.HIGH,     4: TaskPriority.HIGH,
            5: TaskPriority.HIGH,     6: TaskPriority.MEDIUM,
            7: TaskPriority.MEDIUM,   8: TaskPriority.MEDIUM,
        }
        for step_data in steps:
            step_num = getattr(step_data, "step_number", 1)
            task = Task(
                id=uuid.uuid4(),
                company_id=company_id,
                title=f"Step {step_num}: {getattr(step_data, 'title', '')}",
                description=getattr(step_data, "description", ""),
                task_status=TaskStatus.PENDING,
                priority=priority_map.get(step_num, TaskPriority.MEDIUM),
                due_date=date.today() + timedelta(days=getattr(step_data, "days_max", 21)),
                assigned_to=assigned_to,
                source_rescue_step_id=None,  # Set after steps are created
            )
            self.db.add(task)
        await self.db.flush()

    async def get_active_plan(self, company_id: uuid.UUID) -> RescuePlan | None:
        """Get the currently active rescue plan for a company."""
        from sqlalchemy.orm import selectinload
        result = await self.db.execute(
            select(RescuePlan)
            .options(selectinload(RescuePlan.steps))
            .where(
                RescuePlan.company_id == company_id,
                RescuePlan.is_active,
            )
        )
        return result.scalar_one_or_none()

    # ── Step Management ───────────────────────────────────────────

    async def update_step(
        self,
        step_id: uuid.UUID,
        *,
        status: RescueStepStatus,
        completion_notes: str | None = None,
        blocked_reason: str | None = None,
        updated_by: uuid.UUID | None = None,
    ) -> RescueStep | None:
        """
        Update rescue step status.
        COMPLETE status triggers plan progress recalculation.
        Step 8 COMPLETE triggers full compliance re-evaluation.
        """
        result = await self.db.execute(
            select(RescueStep).where(RescueStep.id == step_id)
        )
        step = result.scalar_one_or_none()
        if not step:
            return None

        updates: dict = {
            "step_status": status,
            "updated_by":  updated_by,
        }
        if status == RescueStepStatus.IN_PROGRESS:
            updates["started_at"] = datetime.now(UTC)
        elif status == RescueStepStatus.COMPLETE:
            updates["completed_at"] = datetime.now(UTC)
            updates["completion_notes"] = completion_notes
        elif status == RescueStepStatus.BLOCKED:
            updates["blocked_reason"] = blocked_reason

        for k, v in updates.items():
            if v is not None:
                setattr(step, k, v)
        self.db.add(step)
        await self.db.flush()

        # Recalculate plan progress
        await self._update_plan_progress(step.rescue_plan_id)
        return step

    async def _update_plan_progress(self, plan_id: uuid.UUID) -> None:
        """Recalculate completed_steps, blocked_steps, completion_percentage."""
        result = await self.db.execute(
            select(RescueStep).where(RescueStep.rescue_plan_id == plan_id)
        )
        all_steps = result.scalars().all()
        if not all_steps:
            return

        completed = sum(1 for s in all_steps if s.step_status == RescueStepStatus.COMPLETE)
        blocked = sum(1 for s in all_steps if s.step_status == RescueStepStatus.BLOCKED)
        total = len(all_steps)
        pct = int((completed / total) * 100) if total > 0 else 0

        await self.db.execute(
            update(RescuePlan)
            .where(RescuePlan.id == plan_id)
            .values(
                completed_steps=completed,
                blocked_steps=blocked,
                completion_percentage=pct,
                completed_at=datetime.now(UTC) if completed == total else None,
            )
        )
        await self.db.flush()

    # ── Engagement Creation from Rescue ───────────────────────────

    async def create_engagement_from_rescue(
        self,
        company_id: uuid.UUID,
        rescue_plan: RescuePlan,
        created_by: uuid.UUID | None = None,
    ) -> None:
        """
        Create a revenue engagement when a rescue plan is generated.
        _create_engagement_from_rescue stub implementation.
        AI Constitution Article 2.2: Revenue data visible to admin only.
        """
        from app.services.commercial_service import EngagementService

        eng_svc = EngagementService(self.db)
        await eng_svc.create(
            company_id=company_id,
            engagement_title=rescue_plan.plan_name,
            engagement_type="CORPORATE_RESCUE",
            engagement_status=EngagementStatus.IDENTIFIED,
            revenue_tier=RevenueTier.CORPORATE_RESCUE,
            complexity=ComplexityLevel.CRITICAL,
            triggered_by_risk_band=rescue_plan.initial_risk_band,
            rescue_plan_id=rescue_plan.id,
            identified_date=date.today(),
            assigned_staff_id=rescue_plan.assigned_staff_id,
        )
