"""
NLC - Legal Compliance & Rescue Platform
Layer 2: Statutory Rule Registry
Populated with canonical legal data from seed corpus.
"""
from typing import Any, Dict, List
from enum import Enum

class RuleState(str, Enum):
    COMPLIANT = "COMPLIANT"
    NON_COMPLIANT = "NON_COMPLIANT"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    CONDITIONAL = "CONDITIONAL"
    CONTRADICTORY = "CONTRADICTORY"

class ProvisionStatus(str, Enum):
    RECONCILE = "RECONCILE"
    VERIFIED = "VERIFIED"

STATUTORY_RULE_REGISTRY: Dict[str, Dict[str, Any]] = {
    "INC-001": {
        "rule_id": "INC-001",
        "legal_domain": "Corporate",
        "law": "Section 9, Companies Act 1994 (Bangladesh)",
        "requirement": "Certificate of Incorporation Not Obtained - Company commenced business without Certificate of Incorporation. Section 9: no business until certificate obtained. All pre-certificate contracts void.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 15,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "INC-002": {
        "rule_id": "INC-002",
        "legal_domain": "Corporate",
        "law": "Section 11, Companies Act 1994 (Bangladesh)",
        "requirement": "Memorandum and Articles Not Filed - MoA and AoA not filed with RJSC. Section 11: constitutional documents required. Without filing, company has no valid constitution.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "BLACK",
        "score_impact": 25,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "INC-003": {
        "rule_id": "INC-003",
        "legal_domain": "Corporate",
        "law": "Section 90(2), Companies Act 1994 (Bangladesh)",
        "requirement": "Minimum Directors Not Appointed - Private company has fewer than 2 directors. Section 90(2): minimum 2 required. Cannot validly hold board meetings or pass resolutions.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 15,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "INC-004": {
        "rule_id": "INC-004",
        "legal_domain": "Corporate",
        "law": "Section 150, Companies Act 1994 (Bangladesh)",
        "requirement": "Paid-Up Capital Exceeds Authorized Capital - Paid-up capital exceeds authorized capital. Section 150: company cannot issue shares beyond authorized capital. All excess allotments void.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "BLACK",
        "score_impact": 20,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "INC-005": {
        "rule_id": "INC-005",
        "legal_domain": "Corporate",
        "law": "Section 150, Companies Act 1994; BIDA Foreign Investment Guidelines",
        "requirement": "Encashment Certificate Missing — Foreign Shareholding - Foreign shareholding detected but Encashment Certificate from AD bank not uploaded. Required under BIDA guidelines. CONDITIONAL: Only applies if has_foreign_shareholder == True.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 8,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "INC-006": {
        "rule_id": "INC-006",
        "legal_domain": "Corporate",
        "law": "BIDA Foreign Investment Act 1980; BOI Guidelines",
        "requirement": "Remittance Below Work Permit Threshold - Foreign remittance below USD 50,000 threshold for work permit sponsorship. BIDA registration may be challenged. CONDITIONAL: Only applies if has_foreign_shareholder == True AND bida_registered == True.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AUD-001": {
        "rule_id": "AUD-001",
        "legal_domain": "Corporate",
        "law": "Section 210(1), Companies Act 1994 (Bangladesh)",
        "requirement": "First Auditor Not Appointed Within 30 Days - First auditor not appointed by Board within 30 days of incorporation. Section 210(1): Board must appoint first auditor. Company cannot produce compliant accounts for first AGM.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 10,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AUD-002": {
        "rule_id": "AUD-002",
        "legal_domain": "Corporate",
        "law": "Section 151, Companies Act 1994 (Bangladesh)",
        "requirement": "Audit Not Completed Before AGM - Annual audit not completed before AGM. Section 151: directors must lay audited accounts at AGM. Presenting unaudited accounts renders adoption invalid and exposes directors to liability.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 12,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AUD-003": {
        "rule_id": "AUD-003",
        "legal_domain": "Corporate",
        "law": "Sections 151, 210, Companies Act 1994 (Bangladesh)",
        "requirement": "AGM Held Without Completed Audit — BLACK OVERRIDE - AGM held but no audit completed. Fundamental statutory breach invalidating AGM, accounts, and all resolutions. Company may be liable for fraudulent AGM. BLACK OVERRIDE: forces score to BLACK band. Corporate Rescue mandatory.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "BLACK",
        "score_impact": 25,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AUD-004": {
        "rule_id": "AUD-004",
        "legal_domain": "Corporate",
        "law": "Section 210(2), Companies Act 1994 (Bangladesh)",
        "requirement": "Auditor Not Reappointed at AGM - Auditor not reappointed at AGM. Section 210(2): mandatory at every AGM where accounts presented. Company without appointed auditor cannot file valid annual return.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AGM-001": {
        "rule_id": "AGM-001",
        "legal_domain": "Corporate",
        "law": "Section 77, Companies Act 1994 (Bangladesh)",
        "requirement": "First AGM Default - First AGM not held within 18 months (548 days) of incorporation. Section 81 is mandatory; no waiver for private companies. Default counts from day after deadline.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 20,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AGM-002": {
        "rule_id": "AGM-002",
        "legal_domain": "Corporate",
        "law": "Section 77, Companies Act 1994 (Bangladesh)",
        "requirement": "Subsequent AGM Default - Subsequent AGM not held within 15 months of preceding AGM, or 6 months of FY end — whichever earlier. Section 81 makes no exception for size or dormancy.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 20,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AGM-003": {
        "rule_id": "AGM-003",
        "legal_domain": "Corporate",
        "law": "Section 85, Companies Act 1994 (Bangladesh)",
        "requirement": "AGM Notice Defective — Insufficient Days - AGM notice sent with fewer than 21 clear days before meeting. Section 85 requires 21 clear days. 'Clear days' excludes day of service and day of meeting. Resolutions at improperly noticed AGM may be void.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AGM-004": {
        "rule_id": "AGM-004",
        "legal_domain": "Corporate",
        "law": "Section 85, Companies Act 1994 (Bangladesh)",
        "requirement": "AGM Notice Missing - No written AGM notice sent to members. Section 85 requires notice specifying date, time, place, and business. AGM without proper notice is a nullity — all resolutions void.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 15,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AGM-005": {
        "rule_id": "AGM-005",
        "legal_domain": "Corporate",
        "law": "Section 83(12), Companies Act 1994 (Bangladesh)",
        "requirement": "AGM Quorum Not Met - AGM held but quorum not satisfied. Section 83(12): private companies need minimum 2 members present in person. Resolutions without quorum have no legal effect.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 15,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AGM-006": {
        "rule_id": "AGM-006",
        "legal_domain": "Corporate",
        "law": "Section 83, Companies Act 1994 (Bangladesh)",
        "requirement": "AGM Minutes Not Prepared - AGM held but minutes not prepared or signed by chairman. Section 83: minutes are prima facie evidence of proceedings. Without minutes, AGM validity can be challenged.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AR-001": {
        "rule_id": "AR-001",
        "legal_domain": "Corporate",
        "law": "Section 36, Companies Act 1994 (Bangladesh) – Schedule X",
        "requirement": "Annual Return Default — Single Year - Schedule X (Annual Return) not filed within 21 days of AGM. Section 36 requires the annual summary of share capital and list of members/directors within 21 days. Every officer in default is personally liable to fine for each day of continuing default.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 10,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AR-002": {
        "rule_id": "AR-002",
        "legal_domain": "Corporate",
        "law": "Sections 36 and 304, Companies Act 1994 (Bangladesh)",
        "requirement": "Annual Return 2-Year Backlog - Annual returns unfiled for 2+ consecutive years. Multi-year default increases RJSC enforcement risk. RJSC may commence strike-off under Section 304. Directors face cumulative personal fines.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 20,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AR-003": {
        "rule_id": "AR-003",
        "legal_domain": "Corporate",
        "law": "Sections 36 and 304, Companies Act 1994 (Bangladesh)",
        "requirement": "Annual Return 3-Year Backlog — Strike-Off Risk - Annual returns unfiled for 3+ consecutive years. RJSC has legal basis and practice of initiating strike-off under Section 304. Struck-off company loses legal personality; contracts void, accounts frozen. Corporate Rescue mandatory.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "BLACK",
        "score_impact": 20,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AR-004": {
        "rule_id": "AR-004",
        "legal_domain": "Corporate",
        "law": "Section 36, Companies Act 1994 (Bangladesh) – Schedule X",
        "requirement": "Annual Return Filed But Incomplete - Annual Return filed but missing required attachments: audited financial statements, directors list, members list, or secretary's certificate. Incomplete filing does not satisfy Section 36; company remains in default.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 8,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "DIR-001": {
        "rule_id": "DIR-001",
        "legal_domain": "Corporate",
        "law": "Section 92, Companies Act 1994 (Bangladesh)",
        "requirement": "Director Appointment Not Filed Within 14 Days - Director appointment not filed via Form XII within 14 days. Section 92 requires 14-day filing (NOT 30 days). Until filed, third parties cannot verify director authority, invalidating contracts and resolutions.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 10,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "DIR-002": {
        "rule_id": "DIR-002",
        "legal_domain": "Corporate",
        "law": "Section 92, Companies Act 1994 (Bangladesh)",
        "requirement": "Director Departure Not Filed Within 14 Days - Director resignation/removal/death not filed via Form XII within 14 days. Section 92 requires 14-day filing. Until filed, departed director remains on public record as active, creating liability for post-departure obligations.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 10,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "DIR-003": {
        "rule_id": "DIR-003",
        "legal_domain": "Corporate",
        "law": "Section 92, Companies Act 1994 (Bangladesh)",
        "requirement": "Major Director Filing Irregularity — Over 1 Year - Director change unfiled for over 1 year. Continuing offence under Section 92. Prolonged non-filing creates compounding personal liability. Each day of default adds to statutory fine. Board resolutions may be challenged.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 15,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "DIR-004": {
        "rule_id": "DIR-004",
        "legal_domain": "Corporate",
        "law": "Section 92, Companies Act 1994 (Bangladesh)",
        "requirement": "Departed Director Still Active on RJSC Register - Departed director still recorded as active on RJSC register because Form XII not filed. Departed director continues to bear personal liability for obligations while on record. Enables fraudulent authority claims.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 10,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "SH-001": {
        "rule_id": "SH-001",
        "legal_domain": "Corporate",
        "law": "Section 50, Companies Act 1994 (Bangladesh)",
        "requirement": "Share Allotment Not Filed — Form XV - Share allotment not filed via Form XV within 30 days. Section 50 requires return of allotment. Failure means allotment not reflected in RJSC register, creating uncertainty about issued capital.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 8,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "SH-002": {
        "rule_id": "SH-002",
        "legal_domain": "Corporate",
        "law": "Section 46, Companies Act 1994 (Bangladesh)",
        "requirement": "Share Certificates Not Issued Within 60 Days - Share certificates not issued within 60 days of allotment. Section 46 requires certificates within 2 months. Non-issuance means no documentary evidence of ownership, obstructing transfers and dividends.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "SH-003": {
        "rule_id": "SH-003",
        "legal_domain": "Corporate",
        "law": "Section 52, Companies Act 1994 (Bangladesh)",
        "requirement": "Capital Increase Not Filed — Form IV - Capital increase not filed via Form IV within 30 days of special resolution. Section 52 requires notice of increase. Unrecorded increases cause RJSC records to differ from actual capital.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 8,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "TR-001": {
        "rule_id": "TR-001",
        "legal_domain": "Corporate",
        "law": "Section 108, Companies Act 1994 (Bangladesh)",
        "requirement": "No Share Transfer Instrument — Form 117 - Share transfer without Form 117 instrument. Section 108 requires proper instrument of transfer, duly stamped, executed by both parties. Missing instrument renders transfer void and unregistrable.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "TR-002": {
        "rule_id": "TR-002",
        "legal_domain": "Corporate",
        "law": "Stamp Act 1899 (Bangladesh), Schedule I, Item 62",
        "requirement": "Stamp Duty Not Paid on Share Transfer - Stamp duty not paid on share transfer. Stamp Act 1899 requires ad valorem duty. Unstamped instrument inadmissible in court and cannot be registered. Transferee's ownership unenforceable until duty paid.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "TR-003": {
        "rule_id": "TR-003",
        "legal_domain": "Corporate",
        "law": "Section 47, Companies Act 1994 (Bangladesh); Articles of Association",
        "requirement": "No Board Approval for Share Transfer - Share transfer without board approval where AoA restricts transfer. Section 47 + AoA: board approval required. Transfer in breach is void; transferee has no legal title. Register cannot be validly updated.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 8,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "TR-004": {
        "rule_id": "TR-004",
        "legal_domain": "Corporate",
        "law": "Section 34, Companies Act 1994 (Bangladesh)",
        "requirement": "Register of Members Not Updated After Transfer - Register of Members not updated within 2 months of transfer lodgement. Section 34 requires register update. Until updated, transferee is not recognized member and cannot exercise rights.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "TR-005": {
        "rule_id": "TR-005",
        "legal_domain": "Corporate",
        "law": "Section 47, Companies Act 1994 (Bangladesh); Articles of Association",
        "requirement": "Share Transfer Violates AoA Restriction — BLACK OVERRIDE - Transfer executed in violation of AoA restriction — pre-emption rights not offered, prohibited transferee, or board approval refused. Transfer is void ab initio. Transferee has no legal title. Rectification requires court order or unanimous ratification. BLACK OVERRIDE: forces score to BLACK band. Corporate Rescue mandatory.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "BLACK",
        "score_impact": 15,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "TR-006": {
        "rule_id": "TR-006",
        "legal_domain": "Corporate",
        "law": "Sections 34, 47, 108, Companies Act 1994 (Bangladesh)",
        "requirement": "Composite Irregular Transfer - Transfer has 2+ concurrent deficiencies from TR-001 to TR-005. Composite irregularity compounds legal risk. Each deficiency may independently void transfer. Together they indicate systemic share administration failure requiring structured remediation.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 10,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "REG-001": {
        "rule_id": "REG-001",
        "legal_domain": "Corporate",
        "law": "Sections 34, 83, 87, 90, Companies Act 1994 (Bangladesh)",
        "requirement": "Statutory Registers Incomplete - One or more of 7 mandatory statutory registers not maintained at registered office. Required: Members (Sec 34), Directors (Sec 90), Charges (Sec 87), Transfers (Sec 108), Debentures (Sec 90), AGM Minutes (Sec 83), Board Minutes (Sec 90). Failure is criminal offence; officers personally liable.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "REG-002": {
        "rule_id": "REG-002",
        "legal_domain": "Corporate",
        "law": "Sections 34, 83, 87, 90, Companies Act 1994 (Bangladesh)",
        "requirement": "Core Statutory Registers Missing - Core registers missing: Members (Sec 34), Directors (Sec 90), Charges (Sec 87), or AGM Minutes (Sec 83). These are minimum required for basic corporate governance. Absence indicates fundamental governance failure.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 10,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "REG-003": {
        "rule_id": "REG-003",
        "legal_domain": "Corporate",
        "law": "Section 34(2), Companies Act 1994 (Bangladesh)",
        "requirement": "Registers Not Kept at Registered Office - Statutory registers not at registered office. Section 34(2): registers must be at registered office unless RJSC notified of alternative location. Alternative must be in Bangladesh and Board-approved. Registers open to inspection during business hours.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 3,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "OFF-001": {
        "rule_id": "OFF-001",
        "legal_domain": "Corporate",
        "law": "Section 77, Companies Act 1994 (Bangladesh)",
        "requirement": "Change of Registered Office Not Filed Within 28 Days - Office change not filed via Form VI within 28 days. Section 77 requires 28-day filing (NOT 30 days). Until filed, old address remains legal registered office. Statutory notices served there are valid.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 3,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "CAP-001": {
        "rule_id": "CAP-001",
        "legal_domain": "Corporate",
        "law": "Section 54, Companies Act 1994 (Bangladesh)",
        "requirement": "Capital Alteration Without Proper Resolution - Capital alteration without required board/special resolution, or forms not filed. Section 54 governs capital increase procedure. Unrecorded changes cause RJSC register to differ from actual capital, creating legal uncertainty.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "CAP-002": {
        "rule_id": "CAP-002",
        "legal_domain": "Corporate",
        "law": "Section 87, Companies Act 1994 (Bangladesh)",
        "requirement": "Charge Not Registered With RJSC Within 30 Days - Charge created but not registered via Form VIII within 30 days. Section 87: unregistered charge is void against liquidator and creditors. Lender loses security interest, becomes unsecured creditor. Officers personally liable.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "CAP-003": {
        "rule_id": "CAP-003",
        "legal_domain": "Corporate",
        "law": "Section 87(2), Companies Act 1994 (Bangladesh)",
        "requirement": "Charge Satisfaction Not Filed - Charge paid off but Form XXVIII (Satisfaction) not filed. Section 87(2): file within 30 days of payoff. Until filed, charge remains on register, obstructing future borrowing and creating false security interests.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 3,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "CAP-004": {
        "rule_id": "CAP-004",
        "legal_domain": "Corporate",
        "law": "Section 87, Companies Act 1994 (Bangladesh)",
        "requirement": "Special Resolution Not Filed With RJSC - Special resolution passed but not filed within 30 days. Section 87: every special resolution must be filed. Unfiled resolution not binding on company or enforceable against third parties. Includes capital increase, MoA/AoA alteration, voluntary winding up.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 8,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "TAX-001": {
        "rule_id": "TAX-001",
        "legal_domain": "Tax",
        "law": "Income Tax Act 2023 (Bangladesh)",
        "requirement": "Tax Identification Number (TIN) Not Obtained - No TIN from NBR. Income Tax Act 2023: TIN mandatory for all companies. Without TIN: cannot file returns, open bank accounts, obtain import licenses, participate in tenders, or claim exemptions. Directors may face liability for trading without TIN.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 10,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "TAX-002": {
        "rule_id": "TAX-002",
        "legal_domain": "Tax",
        "law": "Value Added Tax Act 2012 (Bangladesh)",
        "requirement": "VAT Registration Required But Not Obtained - Company exceeds VAT threshold but not registered. VAT Act 2012: registration required above turnover threshold (Tk 30 lakh goods, Tk 15 lakh services). Without VAT: cannot issue tax invoices, claim input credits, or legally supply taxable goods/services. CONDITIONAL: Only applies if estimated turnover exceeds threshold.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "ESC-001": {
        "rule_id": "ESC-001",
        "legal_domain": "Corporate",
        "law": "Section 304, Companies Act 1994 (Bangladesh)",
        "requirement": "Strike-Off Risk Elevated - Compliance profile shows RJSC strike-off criteria under Section 304: multi-year missed filings, no recent trading, or RED flags across 3+ modules. Section 304 permits strike-off for non-filing or non-trading. Structured Regularization required immediately.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 15,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "ESC-002": {
        "rule_id": "ESC-002",
        "legal_domain": "Corporate",
        "law": "Section 304, Companies Act 1994 (Bangladesh)",
        "requirement": "Strike-Off Imminent — BLACK OVERRIDE - Immediate RJSC strike-off risk. Criteria: 3+ years non-filing, strike-off notice received, or on published strike-off list. Once struck off: company ceases to exist, contracts void, accounts frozen. Restoration requires court proceedings under Section 305. Corporate Rescue mandatory. BLACK OVERRIDE: forces score to BLACK band.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "BLACK",
        "score_impact": 25,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "ESC-003": {
        "rule_id": "ESC-003",
        "legal_domain": "Corporate",
        "law": "Section 304, Companies Act 1994 (Bangladesh)",
        "requirement": "Corporate Rescue Mandatory — Systemic Failure - Score below BLACK threshold (<=29) due to systemic multi-module failures: BLACK overrides from AUD-003, TR-005, ESC-002, or RED/YELLOW across 4+ modules. Legal status, contractual capacity, and director exposure all critical. 10-step Corporate Rescue mandatory within 30 days. BLACK OVERRIDE: maintains BLACK until rescue verified.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "BLACK",
        "score_impact": 25,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AGM-007": {
        "rule_id": "AGM-007",
        "legal_domain": "Corporate",
        "law": "Section 84, Companies Act 1994 (Bangladesh)",
        "requirement": "AGM Adjourned Without Proper Notice - AGM adjourned without proper notice. Section 84.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "AUD-005": {
        "rule_id": "AUD-005",
        "legal_domain": "Corporate",
        "law": "Section 210(2), Companies Act 1994 (Bangladesh)",
        "requirement": "Subsequent Auditor Not Appointed - No auditor appointed for current FY. Section 210(2): mandatory at every AGM.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 10,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "BNK-001": {
        "rule_id": "BNK-001",
        "legal_domain": "Corporate",
        "law": "Bankruptcy Act 1997 (Bangladesh), Section 12",
        "requirement": "Winding Up Petition Filed - Winding up petition filed against company. Company under court supervision.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "BLACK",
        "score_impact": 25,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "BNK-002": {
        "rule_id": "BNK-002",
        "legal_domain": "Corporate",
        "law": "Bankruptcy Act 1997 (Bangladesh), Section 14",
        "requirement": "Liquidator Appointed - Liquidator appointed. Company under liquidation proceedings.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "BLACK",
        "score_impact": 25,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "BNK-003": {
        "rule_id": "BNK-003",
        "legal_domain": "Corporate",
        "law": "Bankruptcy Act 1997 (Bangladesh), Section 18",
        "requirement": "Court-Ordered Winding Up - Court-ordered winding up. Company being wound up by court order.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "BLACK",
        "score_impact": 35,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "BSEC-001": {
        "rule_id": "BSEC-001",
        "legal_domain": "Corporate",
        "law": "BSEC Corporate Governance Code 2023, Para 8",
        "requirement": "BSEC Quarterly Report Not Filed - BSEC quarterly report not filed (listed companies only).",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 10,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "BSEC-002": {
        "rule_id": "BSEC-002",
        "legal_domain": "Corporate",
        "law": "BSEC Corporate Governance Code 2023, Para 9",
        "requirement": "CG Certificate Not Obtained - Corporate Governance certificate not obtained (listed companies).",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 10,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "BSEC-003": {
        "rule_id": "BSEC-003",
        "legal_domain": "Corporate",
        "law": "BSEC Corporate Governance Code 2023, Para 5",
        "requirement": "Board Composition Non-Compliant - Board composition non-compliant (independent director requirement).",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 8,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "BSEC-004": {
        "rule_id": "BSEC-004",
        "legal_domain": "Corporate",
        "law": "BSEC Corporate Governance Code 2023, Para 6",
        "requirement": "Audit Committee Not Established - Audit committee not established (listed companies).",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "CHG-001": {
        "rule_id": "CHG-001",
        "legal_domain": "Corporate",
        "law": "Section 87, Companies Act 1994 (Bangladesh)",
        "requirement": "Charge Satisfaction Not Filed - Charge satisfaction not filed via Form XIX. Section 87.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 3,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "DEF-001": {
        "rule_id": "DEF-001",
        "legal_domain": "Corporate",
        "law": "Section 297, Companies Act 1994 (Bangladesh)",
        "requirement": "Director Disqualified - One or more directors disqualified under Section 297. Cannot act as director for 5 years.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "BLACK",
        "score_impact": 20,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "DEF-002": {
        "rule_id": "DEF-002",
        "legal_domain": "Corporate",
        "law": "Section 447, Companies Act 1994 (Bangladesh)",
        "requirement": "Unresolved Penalty Notices - Unresolved penalty notices. Section 447: fine up to Tk 10,000 per offence.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "DIR-005": {
        "rule_id": "DIR-005",
        "legal_domain": "Corporate",
        "law": "Section 97, Companies Act 1994 (Bangladesh)",
        "requirement": "Register of Directors Interests Missing - Register of directors interests not maintained. Section 97.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "DIR-006": {
        "rule_id": "DIR-006",
        "legal_domain": "Corporate",
        "law": "Section 98, Companies Act 1994 (Bangladesh)",
        "requirement": "Register of Contracts Missing - Register of contracts not maintained. Section 98.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "ESC-004": {
        "rule_id": "ESC-004",
        "legal_domain": "Corporate",
        "law": "Section 196, Companies Act 1994 (Bangladesh)",
        "requirement": "Voluntary Winding Up - Voluntary winding up initiated. Section 196.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "BLACK",
        "score_impact": 30,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "ESC-005": {
        "rule_id": "ESC-005",
        "legal_domain": "Corporate",
        "law": "Section 199, Companies Act 1994 (Bangladesh)",
        "requirement": "Investigation Order Pending - Investigation order pending under Section 199.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 20,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "FX-001": {
        "rule_id": "FX-001",
        "legal_domain": "Corporate",
        "law": "Foreign Exchange Regulation Act 1947 (Bangladesh)",
        "requirement": "Foreign Exchange Violation - Foreign exchange violation detected under FE Regulation Act 1947.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 15,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "LBR-001": {
        "rule_id": "LBR-001",
        "legal_domain": "Labour",
        "law": "Labour Act 2006 (Bangladesh), Section 35",
        "requirement": "Factory License Missing - Factory license not obtained. Mandatory for manufacturing entities.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 10,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "LBR-002": {
        "rule_id": "LBR-002",
        "legal_domain": "Labour",
        "law": "Labour Act 2006 (Bangladesh), Section 35",
        "requirement": "Factory License Expired - Factory license expired. Renewal required.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "LBR-003": {
        "rule_id": "LBR-003",
        "legal_domain": "Labour",
        "law": "Labour Act 2006 (Bangladesh), Section 209",
        "requirement": "Labour Court Order Pending - Labour court order pending against the company.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "RED",
        "score_impact": 15,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "STR-001": {
        "rule_id": "STR-001",
        "legal_domain": "Corporate",
        "law": "Section 20, Companies Act 1994 (Bangladesh)",
        "requirement": "Name Change Not Filed - Name change special resolution not filed with RJSC within the statutory period.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 3,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "STR-002": {
        "rule_id": "STR-002",
        "legal_domain": "Corporate",
        "law": "Section 17, Companies Act 1994 (Bangladesh)",
        "requirement": "Object Clause Change Not Filed - MoA object clause change not filed with RJSC.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 3,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "STR-003": {
        "rule_id": "STR-003",
        "legal_domain": "Corporate",
        "law": "Section 18, Companies Act 1994 (Bangladesh)",
        "requirement": "AoA Alteration Not Filed - Articles of Association alteration not filed with RJSC.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 3,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "TAX-003": {
        "rule_id": "TAX-003",
        "legal_domain": "Tax",
        "law": "Income Tax Act 2023, Section 75",
        "requirement": "Annual Tax Return Overdue - Annual income tax return overdue. ITA 2023 Section 75.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "TAX-004": {
        "rule_id": "TAX-004",
        "legal_domain": "Tax",
        "law": "Income Tax Act 2023, Section 74",
        "requirement": "Advance Tax Missed - One or more advance tax quarterly instalments missed. ITA 2023 Section 74.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 3,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "TL-001": {
        "rule_id": "TL-001",
        "legal_domain": "Corporate",
        "law": "City Corporation Ordinance 1983 / Pourashava Act 2009",
        "requirement": "Trade License Not Obtained - Trade License not obtained from City Corporation/Municipality.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "TL-002": {
        "rule_id": "TL-002",
        "legal_domain": "Corporate",
        "law": "City Corporation Ordinance 1983 / Pourashava Act 2009",
        "requirement": "Trade License Expired - Trade License expired. Must renew by 31 March annually.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "VAT-002": {
        "rule_id": "VAT-002",
        "legal_domain": "Tax",
        "law": "Value Added Tax Act 2012 (Bangladesh)",
        "requirement": "Monthly VAT Return Overdue - Monthly/Bi-monthly VAT return overdue.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 8,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
    "VAT-003": {
        "rule_id": "VAT-003",
        "legal_domain": "Tax",
        "law": "Value Added Tax Act 2012 (Bangladesh)",
        "requirement": "VAT Annual Return Overdue - VAT Annual Return overdue for current financial year.",
        "provision": "TBD",
        "provision_status": ProvisionStatus.RECONCILE,
        "applicability": "ALL_ACTIVE_COMPANIES",
        "exceptions": [],
        "evidence_required": ["DOCUMENTARY_EVIDENCE"],
        "evaluation_states": [RuleState.COMPLIANT, RuleState.NON_COMPLIANT, RuleState.UNKNOWN],
        "severity": "YELLOW",
        "score_impact": 5,
        "invariants": ["R-007", "R-008", "R-014", "R-019"]
    },
}

def get_rule(rule_id: str) -> Dict[str, Any] | None:
    return STATUTORY_RULE_REGISTRY.get(rule_id)
