"""seed default document templates

Revision ID: 0008_seed_document_templates
Revises: 0007_fix_tl_inc003_rules
Create Date: 2026-07-03 22:30:00.000000

"""
from alembic import op
import sqlalchemy as sa

revision = '0008_seed_document_templates'
down_revision = '0007_fix_tl_inc003_rules'
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.execute("""
        INSERT INTO ai_prompt_templates 
        (id, template_name, document_type, version, system_prompt, user_prompt_template, 
         liability_disclaimer, is_active, created_at, updated_at)
        VALUES 
        (gen_random_uuid(), 'AGM Minutes', 'AGM_MINUTES', '1.0',
         'You are a legal document assistant for Bangladesh companies. Generate AGM minutes compliant with Companies Act 1994 Section 83.',
         'Generate AGM minutes for {COMPANY_NAME} (Company No: {COMPANY_NUMBER}) for FY {FY}. Date: {DATE}. Directors Present: {DIRECTORS}. Resolutions: {RESOLUTIONS}.',
         'This document was generated by AI and requires human review before distribution. Neum Lex Counsel.',
         true, NOW(), NOW()),
        (gen_random_uuid(), 'Annual Return Form XII', 'ANNUAL_RETURN', '1.0',
         'Generate Annual Return Form XII compliant with Companies Act 1994 Section 119.',
         'Generate Annual Return for {COMPANY_NAME} for FY ending {FY_END}. Directors: {DIRECTORS}. Shareholders: {SHAREHOLDERS}.',
         'This document was generated by AI and requires human review before filing with RJSC. Neum Lex Counsel.',
         true, NOW(), NOW()),
        (gen_random_uuid(), 'Board Resolution', 'BOARD_RESOLUTION', '1.0',
         'Generate a board resolution compliant with Companies Act 1994.',
         'Generate board resolution for {COMPANY_NAME} regarding: {RESOLUTION_TOPIC}. Date: {DATE}.',
         'This document was generated by AI and requires human review before execution. Neum Lex Counsel.',
         true, NOW(), NOW()),
        (gen_random_uuid(), 'Statutory Notice', 'STATUTORY_NOTICE', '1.0',
         'Generate statutory notices for Bangladesh companies compliance.',
         'Generate statutory notice for {COMPANY_NAME} regarding: {NOTICE_TYPE}. Deadline: {DEADLINE}.',
         'This document was generated by AI and requires human review before delivery. Neum Lex Counsel.',
         true, NOW(), NOW()),
        (gen_random_uuid(), 'Engagement Letter', 'ENGAGEMENT_LETTER', '1.0',
         'Generate legal engagement letters for client onboarding.',
         'Generate engagement letter for {COMPANY_NAME}. Scope: {SCOPE}. Fee: {FEE}. Term: {TERM}.',
         'This document was generated by AI and requires human review before execution. Neum Lex Counsel.',
         true, NOW(), NOW())
    """)

def downgrade() -> None:
    op.execute("DELETE FROM ai_prompt_templates WHERE template_name IN ('AGM Minutes', 'Annual Return Form XII', 'Board Resolution', 'Statutory Notice', 'Engagement Letter')")
