"""Reconcile legal_rules to the canonical seed (citations, severity, score, black override)

Revision:  0026_reconcile_rule_law
Previous:  0025_harden_access_table_rls

Generated by tools/gen_rule_sync_migration.py from scripts/seed_rules.py.
Frozen snapshot of 75 rules. Idempotent UPDATE by rule_id; never inserts or deletes.
Aborts if any rule is missing from legal_rules. Downgrade is a no-op (previous
values are not retained).
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0026_reconcile_rule_law"
down_revision: Union[str, None] = "0025_harden_access_table_rls"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (rule_id, rule_name, rule_type, statutory_basis, description, rule_condition_json,
#  default_severity, score_impact, revenue_tier, is_black_override)
RULES = [('INC-001',
  'Certificate of Incorporation Not Obtained',
  'DEADLINE',
  'Section 9, Companies Act 1994 (Bangladesh)',
  'Company commenced business without Certificate of Incorporation. Section 9: no business until certificate '
  'obtained. All pre-certificate contracts void.',
  '{"check_fn": "check_inc_001", "data_points": ["certificate_obtained"], "trigger": "certificate_obtained '
  '== False"}',
  'RED',
  15,
  'STRUCTURED_REGULARIZATION',
  False),
 ('INC-002',
  'Memorandum and Articles Not Filed',
  'DEADLINE',
  'Section 11, Companies Act 1994 (Bangladesh)',
  'MoA and AoA not filed with RJSC. Section 11: constitutional documents required. Without filing, company '
  'has no valid constitution.',
  '{"check_fn": "check_inc_002", "data_points": ["moa_filed", "aoa_filed"], "trigger": "moa_filed == False '
  'OR aoa_filed == False"}',
  'BLACK',
  25,
  'CORPORATE_RESCUE',
  True),
 ('INC-003',
  'Minimum Directors Not Appointed',
  'THRESHOLD',
  'Section 90(2), Companies Act 1994 (Bangladesh)',
  'Private company has fewer than 2 directors. Section 90(2): minimum 2 required. Cannot validly hold board '
  'meetings or pass resolutions.',
  '{"check_fn": "check_inc_003", "data_points": ["company_type", "current_director_count"], "trigger": '
  '"company_type == PRIVATE_LIMITED AND current_director_count < 2"}',
  'BLACK',
  15,
  'STRUCTURED_REGULARIZATION',
  True),
 ('INC-004',
  'Paid-Up Capital Exceeds Authorized Capital',
  'THRESHOLD',
  'Section 150, Companies Act 1994 (Bangladesh)',
  'Paid-up capital exceeds authorized capital. Section 150: company cannot issue shares beyond authorized '
  'capital. All excess allotments void.',
  '{"check_fn": "check_inc_004", "data_points": ["paid_up_capital_bdt", "authorized_capital_bdt"], '
  '"trigger": "paid_up_capital_bdt > authorized_capital_bdt"}',
  'BLACK',
  20,
  'CORPORATE_RESCUE',
  True),
 ('INC-005',
  'Encashment Certificate Missing — Foreign Shareholding',
  'CONDITIONAL',
  'Section 150, Companies Act 1994; BIDA Foreign Investment Guidelines',
  'Foreign shareholding detected but Encashment Certificate from AD bank not uploaded. Required under BIDA '
  'guidelines. CONDITIONAL: Only applies if has_foreign_shareholder == True.',
  '{"check_fn": "check_inc_005", "conditional": true, "data_points": ["has_foreign_shareholder", '
  '"encashment_certificate_uploaded"], "trigger": "has_foreign_shareholder == True AND '
  'encashment_certificate_uploaded == False"}',
  'YELLOW',
  8,
  'COMPLIANCE_PACKAGE',
  False),
 ('INC-006',
  'Remittance Below Work Permit Threshold',
  'CONDITIONAL',
  'BIDA Foreign Investment Act 1980; BOI Guidelines',
  'Foreign remittance below USD 50,000 threshold for work permit sponsorship. BIDA registration may be '
  'challenged. CONDITIONAL: Only applies if has_foreign_shareholder == True AND bida_registered == True.',
  '{"check_fn": "check_inc_006", "conditional": true, "data_points": ["remittance_amount_usd", '
  '"bida_registered"], "trigger": "has_foreign_shareholder == True AND remittance_amount_usd < 50000 AND '
  'bida_registered == True"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('AUD-001',
  'First Auditor Not Appointed Within 30 Days',
  'DEADLINE',
  'Section 210(1), Companies Act 1994 (Bangladesh)',
  'First auditor not appointed by Board within 30 days of incorporation. Section 210(1): Board must appoint '
  'first auditor. Company cannot produce compliant accounts for first AGM.',
  '{"check_fn": "check_aud_001", "data_points": ["first_auditor_appointed", "incorporation_date"], '
  '"trigger": "first_auditor_appointed == False AND days_since_incorporation > 30"}',
  'YELLOW',
  10,
  'COMPLIANCE_PACKAGE',
  False),
 ('AUD-002',
  'Audit Not Completed Before AGM',
  'DEPENDENCY',
  'Section 151, Companies Act 1994 (Bangladesh)',
  'Annual audit not completed before AGM. Section 151: directors must lay audited accounts at AGM. '
  'Presenting unaudited accounts renders adoption invalid and exposes directors to liability.',
  '{"check_fn": "check_aud_002", "data_points": ["agm_held", "audit_complete", "last_agm_date", '
  '"last_audit_signed_date"], "trigger": "agm_held == True AND audit_complete == False"}',
  'RED',
  12,
  'COMPLIANCE_PACKAGE',
  False),
 ('AUD-003',
  'AGM Held Without Completed Audit — BLACK OVERRIDE',
  'DEPENDENCY',
  'Sections 151, 210, Companies Act 1994 (Bangladesh)',
  'AGM held but no audit completed. Fundamental statutory breach invalidating AGM, accounts, and all '
  'resolutions. Company may be liable for fraudulent AGM. BLACK OVERRIDE: forces score to BLACK band. '
  'Corporate Rescue mandatory.',
  '{"check_fn": "check_aud_003", "data_points": ["agm_held", "audit_complete", "agm_held_without_audit"], '
  '"trigger": "agm_held == True AND audit_complete == False AND agm_held_without_audit == True"}',
  'BLACK',
  25,
  'CORPORATE_RESCUE',
  True),
 ('AUD-004',
  'Auditor Not Reappointed at AGM',
  'DEPENDENCY',
  'Section 210(2), Companies Act 1994 (Bangladesh)',
  'Auditor not reappointed at AGM. Section 210(2): mandatory at every AGM where accounts presented. Company '
  'without appointed auditor cannot file valid annual return.',
  '{"check_fn": "check_aud_004", "data_points": ["agm_held", "auditor_reappointed_at_agm"], "trigger": '
  '"agm_held == True AND auditor_reappointed_at_agm == False"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('AGM-001',
  'First AGM Default',
  'DEADLINE',
  'Section 81, Companies Act 1994 (Bangladesh)',
  'First AGM not held within 18 months (548 days) of incorporation. Section 81 is mandatory; no waiver for '
  'private companies. Default counts from day after deadline.',
  '{"check_fn": "check_agm_001", "data_points": ["incorporation_date", "first_agm_held", "agm_count"], '
  '"trigger": "first_agm_held == False AND days_since_incorporation > 548"}',
  'RED',
  20,
  'STRUCTURED_REGULARIZATION',
  False),
 ('AGM-002',
  'Subsequent AGM Default',
  'DEADLINE',
  'Section 81, Companies Act 1994 (Bangladesh)',
  'Subsequent AGM not held within 15 months of preceding AGM, or 6 months of FY end — whichever earlier. '
  'Section 81 makes no exception for size or dormancy.',
  '{"check_fn": "check_agm_002", "data_points": ["last_agm_date", "financial_year_end", "agm_count"], '
  '"trigger": "days_since_last_agm > 456 OR days_since_fy_end > 182"}',
  'RED',
  20,
  'STRUCTURED_REGULARIZATION',
  False),
 ('AGM-003',
  'AGM Notice Defective — Insufficient Days',
  'THRESHOLD',
  'Section 85, Companies Act 1994 (Bangladesh)',
  "AGM notice sent with fewer than 21 clear days before meeting. Section 85 requires 21 clear days. 'Clear "
  "days' excludes day of service and day of meeting. Resolutions at improperly noticed AGM may be void.",
  '{"check_fn": "check_agm_003", "data_points": ["notice_sent_date", "agm_date", "notice_days_before"], '
  '"trigger": "notice_sent_date IS NOT NULL AND notice_days_before < 21"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('AGM-004',
  'AGM Notice Missing',
  'DEADLINE',
  'Section 85, Companies Act 1994 (Bangladesh)',
  'No written AGM notice sent to members. Section 85 requires notice specifying date, time, place, and '
  'business. AGM without proper notice is a nullity — all resolutions void.',
  '{"check_fn": "check_agm_004", "data_points": ["agm_held", "notice_sent_date"], "trigger": "agm_held == '
  'True AND notice_sent_date IS NULL"}',
  'RED',
  15,
  'STRUCTURED_REGULARIZATION',
  False),
 ('AGM-005',
  'AGM Quorum Not Met',
  'THRESHOLD',
  'Section 83(12), Companies Act 1994 (Bangladesh)',
  'AGM held but quorum not satisfied. Section 83(12): private companies need minimum 2 members present in '
  'person. Resolutions without quorum have no legal effect.',
  '{"check_fn": "check_agm_005", "data_points": ["agm_held", "members_present_at_agm", "quorum_required"], '
  '"trigger": "agm_held == True AND members_present < quorum_required"}',
  'RED',
  15,
  'STRUCTURED_REGULARIZATION',
  False),
 ('AGM-006',
  'AGM Minutes Not Prepared',
  'THRESHOLD',
  'Section 83, Companies Act 1994 (Bangladesh)',
  'AGM held but minutes not prepared or signed by chairman. Section 83: minutes are prima facie evidence of '
  'proceedings. Without minutes, AGM validity can be challenged.',
  '{"check_fn": "check_agm_006", "data_points": ["agm_held", "agm_minutes_prepared"], "trigger": "agm_held '
  '== True AND agm_minutes_prepared == False"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('AR-001',
  'Annual Return Default — Single Year',
  'DEADLINE',
  'Section 36, Companies Act 1994 (Bangladesh) – Schedule X',
  'Schedule X (Annual Return) not filed within 21 days of AGM. Section 36 requires the annual summary of '
  'share capital and list of members/directors within 21 days. Every officer in default is personally liable '
  'to fine for each day of continuing default.',
  '{"check_fn": "check_ar_001", "data_points": ["annual_return_filed", "last_agm_date", '
  '"unfiled_returns_count"], "trigger": "annual_return_filed == False AND days_since_agm > 21 AND '
  'unfiled_returns_count == 1"}',
  'YELLOW',
  10,
  'COMPLIANCE_PACKAGE',
  False),
 ('AR-002',
  'Annual Return 2-Year Backlog',
  'ESCALATION',
  'Sections 36 and 304, Companies Act 1994 (Bangladesh)',
  'Annual returns unfiled for 2+ consecutive years. Multi-year default increases RJSC enforcement risk. RJSC '
  'may commence strike-off under Section 304. Directors face cumulative personal fines.',
  '{"check_fn": "check_ar_002", "data_points": ["unfiled_returns_count", "last_return_filed_year"], '
  '"trigger": "unfiled_returns_count >= 2"}',
  'RED',
  20,
  'STRUCTURED_REGULARIZATION',
  False),
 ('AR-003',
  'Annual Return 3-Year Backlog — Strike-Off Risk',
  'ESCALATION',
  'Sections 36 and 304, Companies Act 1994 (Bangladesh)',
  'Annual returns unfiled for 3+ consecutive years. RJSC has legal basis and practice of initiating '
  'strike-off under Section 304. Struck-off company loses legal personality; contracts void, accounts '
  'frozen. Corporate Rescue mandatory.',
  '{"check_fn": "check_ar_003", "data_points": ["unfiled_returns_count", "last_return_filed_year"], '
  '"trigger": "unfiled_returns_count >= 3"}',
  'BLACK',
  20,
  'CORPORATE_RESCUE',
  False),
 ('AR-004',
  'Annual Return Filed But Incomplete',
  'THRESHOLD',
  'Section 36, Companies Act 1994 (Bangladesh) – Schedule X',
  'Annual Return filed but missing required attachments: audited financial statements, directors list, '
  "members list, or secretary's certificate. Incomplete filing does not satisfy Section 36; company remains "
  'in default.',
  '{"check_fn": "check_ar_004", "data_points": ["annual_return_filed", "annual_return_content_complete"], '
  '"trigger": "annual_return_filed == True AND annual_return_content_complete == False"}',
  'YELLOW',
  8,
  'COMPLIANCE_PACKAGE',
  False),
 ('DIR-001',
  'Director Appointment Not Filed Within 14 Days',
  'DEADLINE',
  'Section 92, Companies Act 1994 (Bangladesh)',
  'Director appointment not filed via Form XII within 14 days. Section 92 requires 14-day filing (NOT 30 '
  'days). Until filed, third parties cannot verify director authority, invalidating contracts and '
  'resolutions.',
  '{"check_fn": "check_dir_001", "data_points": ["director_changes", "appointment_date", '
  '"appointment_delay_days"], "trigger": "director_change_type == APPOINTMENT AND appointment_delay_days > '
  '14"}',
  'YELLOW',
  10,
  'COMPLIANCE_PACKAGE',
  False),
 ('DIR-002',
  'Director Departure Not Filed Within 14 Days',
  'DEADLINE',
  'Section 92, Companies Act 1994 (Bangladesh)',
  'Director resignation/removal/death not filed via Form XII within 14 days. Section 92 requires 14-day '
  'filing. Until filed, departed director remains on public record as active, creating liability for '
  'post-departure obligations.',
  '{"check_fn": "check_dir_002", "data_points": ["director_changes", "departure_date", '
  '"departure_delay_days"], "trigger": "director_change_type == DEPARTURE AND departure_delay_days > 14"}',
  'YELLOW',
  10,
  'COMPLIANCE_PACKAGE',
  False),
 ('DIR-003',
  'Major Director Filing Irregularity — Over 1 Year',
  'ESCALATION',
  'Section 92, Companies Act 1994 (Bangladesh)',
  'Director change unfiled for over 1 year. Continuing offence under Section 92. Prolonged non-filing '
  'creates compounding personal liability. Each day of default adds to statutory fine. Board resolutions may '
  'be challenged.',
  '{"check_fn": "check_dir_003", "data_points": ["director_changes", "appointment_delay_days", '
  '"departure_delay_days"], "trigger": "director_filing_delay_days > 365"}',
  'RED',
  15,
  'STRUCTURED_REGULARIZATION',
  False),
 ('DIR-004',
  'Departed Director Still Active on RJSC Register',
  'DEPENDENCY',
  'Section 92, Companies Act 1994 (Bangladesh)',
  'Departed director still recorded as active on RJSC register because Form XII not filed. Departed director '
  'continues to bear personal liability for obligations while on record. Enables fraudulent authority '
  'claims.',
  '{"check_fn": "check_dir_004", "data_points": ["director_changes", "departed_still_liable"], "trigger": '
  '"departed_still_liable == True"}',
  'RED',
  10,
  'STRUCTURED_REGULARIZATION',
  False),
 ('SH-001',
  'Share Allotment Not Filed — Form XV',
  'DEADLINE',
  'Section 50, Companies Act 1994 (Bangladesh)',
  'Share allotment not filed via Form XV within 30 days. Section 50 requires return of allotment. Failure '
  'means allotment not reflected in RJSC register, creating uncertainty about issued capital.',
  '{"check_fn": "check_sh_001", "data_points": ["last_allotment_date", "form_xv_filed"], "trigger": '
  '"last_allotment_date IS NOT NULL AND form_xv_filed == False AND days_since_allotment > 30"}',
  'YELLOW',
  8,
  'COMPLIANCE_PACKAGE',
  False),
 ('SH-002',
  'Share Certificates Not Issued Within 60 Days',
  'DEADLINE',
  'Section 46, Companies Act 1994 (Bangladesh)',
  'Share certificates not issued within 60 days of allotment. Section 46 requires certificates within 2 '
  'months. Non-issuance means no documentary evidence of ownership, obstructing transfers and dividends.',
  '{"check_fn": "check_sh_002", "data_points": ["share_certificates_issued", "last_allotment_date"], '
  '"trigger": "share_certificates_issued == False AND last_allotment_date IS NOT NULL AND '
  'days_since_allotment > 60"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('SH-003',
  'Capital Increase Not Filed — Form IV',
  'DEADLINE',
  'Section 52, Companies Act 1994 (Bangladesh)',
  'Capital increase not filed via Form IV within 30 days of special resolution. Section 52 requires notice '
  'of increase. Unrecorded increases cause RJSC records to differ from actual capital.',
  '{"check_fn": "check_sh_003", "data_points": ["capital_increase_date", "form_iv_filed"], "trigger": '
  '"capital_increase_date IS NOT NULL AND form_iv_filed == False AND days_since_capital_increase > 30"}',
  'YELLOW',
  8,
  'COMPLIANCE_PACKAGE',
  False),
 ('TR-001',
  'No Share Transfer Instrument — Form 117',
  'THRESHOLD',
  'Section 108, Companies Act 1994 (Bangladesh)',
  'Share transfer without Form 117 instrument. Section 108 requires proper instrument of transfer, duly '
  'stamped, executed by both parties. Missing instrument renders transfer void and unregistrable.',
  '{"check_fn": "check_tr_001", "data_points": ["share_transfers", "has_instrument"], "trigger": '
  '"has_instrument == False"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('TR-002',
  'Stamp Duty Not Paid on Share Transfer',
  'THRESHOLD',
  'Stamp Act 1899 (Bangladesh), Schedule I, Item 62',
  'Stamp duty not paid on share transfer. Stamp Act 1899 requires ad valorem duty. Unstamped instrument '
  "inadmissible in court and cannot be registered. Transferee's ownership unenforceable until duty paid.",
  '{"check_fn": "check_tr_002", "data_points": ["share_transfers", "stamp_paid"], "trigger": "has_instrument '
  '== True AND stamp_paid == False"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('TR-003',
  'No Board Approval for Share Transfer',
  'THRESHOLD',
  'Section 47, Companies Act 1994 (Bangladesh); Articles of Association',
  'Share transfer without board approval where AoA restricts transfer. Section 47 + AoA: board approval '
  'required. Transfer in breach is void; transferee has no legal title. Register cannot be validly updated.',
  '{"check_fn": "check_tr_003", "data_points": ["share_transfers", "board_approved", '
  '"aoa_transfer_restriction"], "trigger": "board_approved == False AND aoa_transfer_restriction == True"}',
  'YELLOW',
  8,
  'COMPLIANCE_PACKAGE',
  False),
 ('TR-004',
  'Register of Members Not Updated After Transfer',
  'DEADLINE',
  'Section 34, Companies Act 1994 (Bangladesh)',
  'Register of Members not updated within 2 months of transfer lodgement. Section 34 requires register '
  'update. Until updated, transferee is not recognized member and cannot exercise rights.',
  '{"check_fn": "check_tr_004", "data_points": ["share_transfers", "register_updated", "transfer_date"], '
  '"trigger": "register_updated == False AND transfer_date IS NOT NULL"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('TR-005',
  'Share Transfer Violates AoA Restriction — BLACK OVERRIDE',
  'THRESHOLD',
  'Section 47, Companies Act 1994 (Bangladesh); Articles of Association',
  'Transfer executed in violation of AoA restriction — pre-emption rights not offered, prohibited '
  'transferee, or board approval refused. Transfer is void ab initio. Transferee has no legal title. '
  'Rectification requires court order or unanimous ratification. BLACK OVERRIDE: forces score to BLACK band. '
  'Corporate Rescue mandatory.',
  '{"check_fn": "check_tr_005", "data_points": ["share_transfers", "aoa_violated"], "trigger": "aoa_violated '
  '== True"}',
  'BLACK',
  15,
  'CORPORATE_RESCUE',
  True),
 ('TR-006',
  'Composite Irregular Transfer',
  'CASCADE',
  'Sections 34, 47, 108, Companies Act 1994 (Bangladesh)',
  'Transfer has 2+ concurrent deficiencies from TR-001 to TR-005. Composite irregularity compounds legal '
  'risk. Each deficiency may independently void transfer. Together they indicate systemic share '
  'administration failure requiring structured remediation.',
  '{"check_fn": "check_tr_006", "data_points": ["share_transfers", "is_irregular"], "trigger": "is_irregular '
  '== True AND irregularity_count >= 2"}',
  'RED',
  10,
  'STRUCTURED_REGULARIZATION',
  False),
 ('REG-001',
  'Statutory Registers Incomplete',
  'THRESHOLD',
  'Sections 34, 83, 87, 90, Companies Act 1994 (Bangladesh)',
  'One or more of 7 mandatory statutory registers not maintained at registered office. Required: Members '
  '(Sec 34), Directors (Sec 90), Charges (Sec 87), Transfers (Sec 108), Debentures (Sec 90), AGM Minutes '
  '(Sec 83), Board Minutes (Sec 90). Failure is criminal offence; officers personally liable.',
  '{"check_fn": "check_reg_001", "data_points": ["maintained_registers"], "trigger": '
  '"len(maintained_registers) < 7"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('REG-002',
  'Core Statutory Registers Missing',
  'THRESHOLD',
  'Sections 34, 83, 87, 90, Companies Act 1994 (Bangladesh)',
  'Core registers missing: Members (Sec 34), Directors (Sec 90), Charges (Sec 87), or AGM Minutes (Sec 83). '
  'These are minimum required for basic corporate governance. Absence indicates fundamental governance '
  'failure.',
  '{"check_fn": "check_reg_002", "data_points": ["register_of_members_maintained", '
  '"register_of_directors_maintained", "register_of_charges_maintained", "minutes_book_agm_maintained"], '
  '"trigger": "members_register_missing == True OR directors_register_missing == True OR '
  'charges_register_missing == True OR minutes_agm_missing == True"}',
  'RED',
  10,
  'STRUCTURED_REGULARIZATION',
  False),
 ('REG-003',
  'Registers Not Kept at Registered Office',
  'THRESHOLD',
  'Section 34(2), Companies Act 1994 (Bangladesh)',
  'Statutory registers not at registered office. Section 34(2): registers must be at registered office '
  'unless RJSC notified of alternative location. Alternative must be in Bangladesh and Board-approved. '
  'Registers open to inspection during business hours.',
  '{"check_fn": "check_reg_003", "data_points": ["register_location", "alternative_location_notified"], '
  '"trigger": "register_location != registered_office AND alternative_location_notified == False"}',
  'YELLOW',
  3,
  'COMPLIANCE_PACKAGE',
  False),
 ('OFF-001',
  'Change of Registered Office Not Filed Within 28 Days',
  'DEADLINE',
  'Section 77, Companies Act 1994 (Bangladesh)',
  'Office change not filed via Form VI within 28 days. Section 77 requires 28-day filing (NOT 30 days). '
  'Until filed, old address remains legal registered office. Statutory notices served there are valid.',
  '{"check_fn": "check_off_001", "data_points": ["registered_office_change_date", "form_vi_filed"], '
  '"trigger": "registered_office_change_date IS NOT NULL AND form_vi_filed == False AND '
  'days_since_office_change > 28"}',
  'YELLOW',
  3,
  'COMPLIANCE_PACKAGE',
  False),
 ('CAP-001',
  'Capital Alteration Without Proper Resolution',
  'CASCADE',
  'Section 54, Companies Act 1994 (Bangladesh)',
  'Capital alteration without required board/special resolution, or forms not filed. Section 54 governs '
  'capital increase procedure. Unrecorded changes cause RJSC register to differ from actual capital, '
  'creating legal uncertainty.',
  '{"check_fn": "check_cap_001", "data_points": ["capital_increase_date", "capital_increase_resolution"], '
  '"trigger": "capital_increase_date IS NOT NULL AND capital_increase_resolution == False"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('CAP-002',
  'Charge Not Registered With RJSC Within 30 Days',
  'DEADLINE',
  'Section 87, Companies Act 1994 (Bangladesh)',
  'Charge created but not registered via Form VIII within 30 days. Section 87: unregistered charge is void '
  'against liquidator and creditors. Lender loses security interest, becomes unsecured creditor. Officers '
  'personally liable.',
  '{"check_fn": "check_cap_002", "data_points": ["charge_creation_date", "form_viii_filed"], "trigger": '
  '"charge_creation_date IS NOT NULL AND form_viii_filed == False AND days_since_charge_creation > 30"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('CAP-003',
  'Capital Reduction Without Court Order',
  'CASCADE',
  'Section 100, Companies Act 1994 (Bangladesh)',
  'Capital reduction without court order. Section 100: court confirmation required. Without it, reduction is '
  'void, directors personally liable.',
  '{"check_fn": "check_cap_003", "data_points": ["capital_reduction_pending", '
  '"capital_reduction_court_order_obtained"], "trigger": "capital_reduction_pending == True AND '
  'capital_reduction_court_order_obtained == False"}',
  'BLACK',
  15,
  'CORPORATE_RESCUE',
  True),
 ('CAP-004',
  'Special Resolution Not Filed With RJSC',
  'DEADLINE',
  'Section 87, Companies Act 1994 (Bangladesh)',
  'Special resolution passed but not filed within 30 days. Section 87: every special resolution must be '
  'filed. Unfiled resolution not binding on company or enforceable against third parties. Includes capital '
  'increase, MoA/AoA alteration, voluntary winding up.',
  '{"check_fn": "check_cap_004", "data_points": ["special_resolution_date", "form_viii_filed"], "trigger": '
  '"special_resolution_date IS NOT NULL AND form_viii_filed == False AND days_since_resolution > 30"}',
  'YELLOW',
  8,
  'COMPLIANCE_PACKAGE',
  False),
 ('TAX-001',
  'Tax Identification Number (TIN) Not Obtained',
  'THRESHOLD',
  'Income Tax Act 2023 (Bangladesh)',
  'No TIN from NBR. Income Tax Act 2023: TIN mandatory for all companies. Without TIN: cannot file returns, '
  'open bank accounts, obtain import licenses, participate in tenders, or claim exemptions. Directors may '
  'face liability for trading without TIN.',
  '{"check_fn": "check_tax_001", "data_points": ["tin_obtained", "tin_number"], "trigger": "tin_obtained == '
  'False"}',
  'RED',
  10,
  'STRUCTURED_REGULARIZATION',
  False),
 ('TAX-002',
  'VAT Registration Required But Not Obtained',
  'CONDITIONAL',
  'Value Added Tax Act 2012 (Bangladesh)',
  'Company exceeds VAT threshold but not registered. VAT Act 2012: registration required above turnover '
  'threshold (Tk 30 lakh goods, Tk 15 lakh services). Without VAT: cannot issue tax invoices, claim input '
  'credits, or legally supply taxable goods/services. CONDITIONAL: Only applies if estimated turnover '
  'exceeds threshold.',
  '{"check_fn": "check_tax_002", "conditional": true, "data_points": ["vat_registered", '
  '"estimated_turnover_bdt"], "trigger": "vat_registered == False AND estimated_turnover_bdt > 3000000"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('ESC-001',
  'Strike-Off Risk Elevated',
  'ESCALATION',
  'Section 304, Companies Act 1994 (Bangladesh)',
  'Compliance profile shows RJSC strike-off criteria under Section 304: multi-year missed filings, no recent '
  'trading, or RED flags across 3+ modules. Section 304 permits strike-off for non-filing or non-trading. '
  'Structured Regularization required immediately.',
  '{"check_fn": "check_esc_001", "data_points": ["unfiled_returns_count", "active_red_flags", '
  '"active_yellow_flags"], "trigger": "unfiled_returns_count >= 2 OR (active_red_flags >= 3 AND '
  'active_yellow_flags >= 4)"}',
  'RED',
  15,
  'STRUCTURED_REGULARIZATION',
  False),
 ('ESC-002',
  'Strike-Off Imminent — BLACK OVERRIDE',
  'ESCALATION',
  'Section 304, Companies Act 1994 (Bangladesh)',
  'Immediate RJSC strike-off risk. Criteria: 3+ years non-filing, strike-off notice received, or on '
  'published strike-off list. Once struck off: company ceases to exist, contracts void, accounts frozen. '
  'Restoration requires court proceedings under Section 305. Corporate Rescue mandatory. BLACK OVERRIDE: '
  'forces score to BLACK band.',
  '{"check_fn": "check_esc_002", "data_points": ["unfiled_returns_count", "rjsc_strike_off_notice", '
  '"on_rjsc_strike_off_list"], "trigger": "unfiled_returns_count >= 3 OR rjsc_strike_off_notice == True OR '
  'on_rjsc_strike_off_list == True"}',
  'BLACK',
  25,
  'CORPORATE_RESCUE',
  True),
 ('ESC-003',
  'Corporate Rescue Mandatory — Systemic Failure',
  'ESCALATION',
  'Section 304, Companies Act 1994 (Bangladesh)',
  'Score below BLACK threshold (<=29) due to systemic multi-module failures: BLACK overrides from AUD-003, '
  'TR-005, ESC-002, or RED/YELLOW across 4+ modules. Legal status, contractual capacity, and director '
  'exposure all critical. 10-step Corporate Rescue mandatory within 30 days. BLACK OVERRIDE: maintains BLACK '
  'until rescue verified.',
  '{"check_fn": "check_esc_003", "data_points": ["pre_override_score", "has_black_override", '
  '"active_red_flags", "active_black_flags"], "trigger": "pre_override_score <= 29 OR has_black_override == '
  'True"}',
  'BLACK',
  25,
  'CORPORATE_RESCUE',
  True),
 ('AGM-007',
  'AGM Adjourned Without Proper Notice',
  'THRESHOLD',
  'Section 84, Companies Act 1994 (Bangladesh)',
  'AGM adjourned without proper notice. Section 84.',
  '{"check_fn": "check_agm_007", "data_points": ["agm_adjourned_without_notice"], "trigger": '
  '"agm_adjourned_without_notice == True"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('AUD-005',
  'Subsequent Auditor Not Appointed',
  'DEPENDENCY',
  'Section 210(2), Companies Act 1994 (Bangladesh)',
  'No auditor appointed for current FY. Section 210(2): mandatory at every AGM.',
  '{"check_fn": "check_aud_005", "data_points": ["agm_count", "auditor_reappointed_at_agm"], "trigger": '
  '"agm_count > 0 AND auditor_reappointed_at_agm == False"}',
  'RED',
  10,
  'STRUCTURED_REGULARIZATION',
  False),
 ('BNK-001',
  'Winding Up Petition Filed',
  'THRESHOLD',
  'Bankruptcy Act 1997 (Bangladesh), Section 12',
  'Winding up petition filed against company. Company under court supervision.',
  '{"check_fn": "check_bnk_001", "data_points": ["winding_up_petition_filed"], "trigger": '
  '"winding_up_petition_filed == True"}',
  'BLACK',
  25,
  'CORPORATE_RESCUE',
  True),
 ('BNK-002',
  'Liquidator Appointed',
  'THRESHOLD',
  'Bankruptcy Act 1997 (Bangladesh), Section 14',
  'Liquidator appointed. Company under liquidation proceedings.',
  '{"check_fn": "check_bnk_002", "data_points": ["liquidator_appointed"], "trigger": "liquidator_appointed '
  '== True"}',
  'BLACK',
  25,
  'CORPORATE_RESCUE',
  True),
 ('BNK-003',
  'Court-Ordered Winding Up',
  'THRESHOLD',
  'Bankruptcy Act 1997 (Bangladesh), Section 18',
  'Court-ordered winding up. Company being wound up by court order.',
  '{"check_fn": "check_bnk_003", "data_points": ["court_ordered_winding_up"], "trigger": '
  '"court_ordered_winding_up == True"}',
  'BLACK',
  35,
  'CORPORATE_RESCUE',
  True),
 ('BSEC-001',
  'BSEC Quarterly Report Not Filed',
  'DEADLINE',
  'BSEC Corporate Governance Code 2023, Para 8',
  'BSEC quarterly report not filed (listed companies only).',
  '{"check_fn": "check_bsec_001", "conditional": true, "data_points": ["bsec_listed", '
  '"bsec_quarterly_report_filed"], "trigger": "bsec_listed == True AND bsec_quarterly_report_filed == '
  'False"}',
  'RED',
  10,
  'STRUCTURED_REGULARIZATION',
  False),
 ('BSEC-002',
  'CG Certificate Not Obtained',
  'THRESHOLD',
  'BSEC Corporate Governance Code 2023, Para 9',
  'Corporate Governance certificate not obtained (listed companies).',
  '{"check_fn": "check_bsec_002", "conditional": true, "data_points": ["bsec_listed", '
  '"cg_certificate_obtained"], "trigger": "bsec_listed == True AND cg_certificate_obtained == False"}',
  'RED',
  10,
  'STRUCTURED_REGULARIZATION',
  False),
 ('BSEC-003',
  'Board Composition Non-Compliant',
  'THRESHOLD',
  'BSEC Corporate Governance Code 2023, Para 5',
  'Board composition non-compliant (independent director requirement).',
  '{"check_fn": "check_bsec_003", "conditional": true, "data_points": ["bsec_listed", '
  '"board_independent_director"], "trigger": "bsec_listed == True AND board_independent_director == False"}',
  'YELLOW',
  8,
  'COMPLIANCE_PACKAGE',
  False),
 ('BSEC-004',
  'Audit Committee Not Established',
  'THRESHOLD',
  'BSEC Corporate Governance Code 2023, Para 6',
  'Audit committee not established (listed companies).',
  '{"check_fn": "check_bsec_004", "conditional": true, "data_points": ["bsec_listed", '
  '"audit_committee_established"], "trigger": "bsec_listed == True AND audit_committee_established == '
  'False"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('CHG-001',
  'Charge Satisfaction Not Filed',
  'DEADLINE',
  'Section 87, Companies Act 1994 (Bangladesh)',
  'Charge satisfaction not filed via Form XIX. Section 87.',
  '{"check_fn": "check_chg_001", "data_points": ["charges"], "trigger": "charge_satisfied == True AND '
  'satisfaction_filed == False"}',
  'YELLOW',
  3,
  'COMPLIANCE_PACKAGE',
  False),
 ('DEF-001',
  'Director Disqualified',
  'THRESHOLD',
  'Section 297, Companies Act 1994 (Bangladesh)',
  'One or more directors disqualified under Section 297. Cannot act as director for 5 years.',
  '{"check_fn": "check_def_001", "data_points": ["any_director_disqualified", "disqualification_details"], '
  '"trigger": "any_director_disqualified == True"}',
  'BLACK',
  20,
  'CORPORATE_RESCUE',
  True),
 ('DEF-002',
  'Unresolved Penalty Notices',
  'ESCALATION',
  'Section 447, Companies Act 1994 (Bangladesh)',
  'Unresolved penalty notices. Section 447: fine up to Tk 10,000 per offence.',
  '{"check_fn": "check_def_002", "data_points": ["penalty_notices_received", "penalty_notices_resolved"], '
  '"trigger": "penalty_notices_received > penalty_notices_resolved"}',
  'YELLOW',
  5,
  'STRUCTURED_REGULARIZATION',
  False),
 ('DIR-005',
  'Register of Directors Interests Missing',
  'THRESHOLD',
  'Section 97, Companies Act 1994 (Bangladesh)',
  'Register of directors interests not maintained. Section 97.',
  '{"check_fn": "check_dir_005", "data_points": ["register_of_directors_interests"], "trigger": '
  '"register_of_directors_interests == False"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('DIR-006',
  'Register of Contracts Missing',
  'THRESHOLD',
  'Section 98, Companies Act 1994 (Bangladesh)',
  'Register of contracts not maintained. Section 98.',
  '{"check_fn": "check_dir_006", "data_points": ["register_of_contracts"], "trigger": "register_of_contracts '
  '== False"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('ESC-004',
  'Voluntary Winding Up',
  'THRESHOLD',
  'Section 196, Companies Act 1994 (Bangladesh)',
  'Voluntary winding up initiated. Section 196.',
  '{"check_fn": "check_esc_004", "data_points": ["voluntary_winding_up"], "trigger": "voluntary_winding_up '
  '== True"}',
  'BLACK',
  30,
  'CORPORATE_RESCUE',
  True),
 ('ESC-005',
  'Investigation Order Pending',
  'THRESHOLD',
  'Section 199, Companies Act 1994 (Bangladesh)',
  'Investigation order pending under Section 199.',
  '{"check_fn": "check_esc_005", "data_points": ["investigation_order"], "trigger": "investigation_order == '
  'True"}',
  'RED',
  20,
  'STRUCTURED_REGULARIZATION',
  False),
 ('FX-001',
  'Foreign Exchange Violation',
  'THRESHOLD',
  'Foreign Exchange Regulation Act 1947 (Bangladesh)',
  'Foreign exchange violation detected under FE Regulation Act 1947.',
  '{"check_fn": "check_fx_001", "data_points": ["foreign_exchange_violation"], "trigger": '
  '"foreign_exchange_violation == True"}',
  'RED',
  15,
  'STRUCTURED_REGULARIZATION',
  False),
 ('LBR-001',
  'Factory License Missing',
  'THRESHOLD',
  'Labour Act 2006 (Bangladesh), Section 35',
  'Factory license not obtained. Mandatory for manufacturing entities.',
  '{"check_fn": "check_lbr_001", "data_points": ["factory_license_obtained"], "trigger": '
  '"factory_license_obtained == False"}',
  'RED',
  10,
  'STRUCTURED_REGULARIZATION',
  False),
 ('LBR-002',
  'Factory License Expired',
  'DEADLINE',
  'Labour Act 2006 (Bangladesh), Section 35',
  'Factory license expired. Renewal required.',
  '{"check_fn": "check_lbr_002", "data_points": ["factory_license_expiry"], "trigger": '
  '"factory_license_expiry < today"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('LBR-003',
  'Labour Court Order Pending',
  'THRESHOLD',
  'Labour Act 2006 (Bangladesh), Section 209',
  'Labour court order pending against the company.',
  '{"check_fn": "check_lbr_003", "data_points": ["labour_court_order_pending"], "trigger": '
  '"labour_court_order_pending == True"}',
  'RED',
  15,
  'STRUCTURED_REGULARIZATION',
  False),
 ('STR-001',
  'Name Change Not Filed',
  'DEADLINE',
  'Section 20, Companies Act 1994 (Bangladesh)',
  'Name change special resolution not filed with RJSC within the statutory period.',
  '{"check_fn": "check_str_001", "data_points": ["name_change_pending", "name_change_date"], "trigger": '
  '"name_change_pending == True AND days_since_name_change > 30"}',
  'YELLOW',
  3,
  'COMPLIANCE_PACKAGE',
  False),
 ('STR-002',
  'Object Clause Change Not Filed',
  'DEADLINE',
  'Section 17, Companies Act 1994 (Bangladesh)',
  'MoA object clause change not filed with RJSC.',
  '{"check_fn": "check_str_002", "data_points": ["object_clause_change_pending", '
  '"object_clause_change_date"], "trigger": "object_clause_change_pending == True AND '
  'days_since_object_change > 30"}',
  'YELLOW',
  3,
  'COMPLIANCE_PACKAGE',
  False),
 ('STR-003',
  'AoA Alteration Not Filed',
  'DEADLINE',
  'Section 18, Companies Act 1994 (Bangladesh)',
  'Articles of Association alteration not filed with RJSC.',
  '{"check_fn": "check_str_003", "data_points": ["aoa_alteration_pending", "aoa_alteration_date"], '
  '"trigger": "aoa_alteration_pending == True AND days_since_aoa_alteration > 30"}',
  'YELLOW',
  3,
  'COMPLIANCE_PACKAGE',
  False),
 ('TAX-003',
  'Annual Tax Return Overdue',
  'DEADLINE',
  'Income Tax Act 2023, Section 75',
  'Annual income tax return overdue. ITA 2023 Section 75.',
  '{"check_fn": "check_tax_003", "data_points": ["tax_return_filed_for_current_fy", '
  '"last_tax_return_filed"], "trigger": "tax_return_filed_for_current_fy == False AND past_deadline"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('TAX-004',
  'Advance Tax Missed',
  'DEADLINE',
  'Income Tax Act 2023, Section 74',
  'One or more advance tax quarterly instalments missed. ITA 2023 Section 74.',
  '{"check_fn": "check_tax_004", "data_points": ["advance_tax_q1_paid", "advance_tax_q2_paid", '
  '"advance_tax_q3_paid", "advance_tax_q4_paid"], "trigger": "advance_tax_missed == True"}',
  'YELLOW',
  3,
  'COMPLIANCE_PACKAGE',
  False),
 ('TL-001',
  'Trade License Not Obtained',
  'THRESHOLD',
  'City Corporation Ordinance 1983 / Pourashava Act 2009',
  'Trade License not obtained from City Corporation/Municipality.',
  '{"check_fn": "check_tl_001", "data_points": ["trade_license_obtained"], "trigger": '
  '"trade_license_obtained == False"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('TL-002',
  'Trade License Expired',
  'DEADLINE',
  'City Corporation Ordinance 1983 / Pourashava Act 2009',
  'Trade License expired. Must renew by 31 March annually.',
  '{"check_fn": "check_tl_002", "data_points": ["trade_license_expiry"], "trigger": "trade_license_expiry < '
  'today"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False),
 ('VAT-002',
  'Monthly VAT Return Overdue',
  'DEADLINE',
  'Value Added Tax Act 2012 (Bangladesh)',
  'Monthly/Bi-monthly VAT return overdue.',
  '{"check_fn": "check_vat_002", "data_points": ["vat_registered", "last_vat_return_filed"], "trigger": '
  '"vat_registered == True AND monthly_vat_overdue == True"}',
  'YELLOW',
  8,
  'COMPLIANCE_PACKAGE',
  False),
 ('VAT-003',
  'VAT Annual Return Overdue',
  'DEADLINE',
  'Value Added Tax Act 2012 (Bangladesh)',
  'VAT Annual Return overdue for current financial year.',
  '{"check_fn": "check_vat_003", "data_points": ["vat_registered", "vat_annual_return_filed_for_fy"], '
  '"trigger": "vat_registered == True AND vat_annual_return_filed_for_fy == False"}',
  'YELLOW',
  5,
  'COMPLIANCE_PACKAGE',
  False)]


def upgrade() -> None:
    conn = op.get_bind()
    missing = []
    for (rule_id, name, rtype, basis, descr, cond, sev, score, tier, black) in RULES:
        res = conn.execute(sa.text("""
            UPDATE legal_rules SET
                rule_name         = :name,
                rule_type         = CAST(:rtype AS rule_type),
                statutory_basis   = :basis,
                description       = :descr,
                rule_condition    = CAST(:cond AS jsonb),
                default_severity  = CAST(:sev AS severity_level),
                score_impact      = :score,
                revenue_tier      = CAST(:tier AS revenue_tier),
                is_black_override = :black,
                is_active         = TRUE,
                updated_at        = NOW()
            WHERE rule_id = :rid
        """), {
            "rid": rule_id, "name": name, "rtype": rtype, "basis": basis, "descr": descr,
            "cond": cond, "sev": sev, "score": score, "tier": tier, "black": black,
        })
        if res.rowcount != 1:
            missing.append(rule_id)
    if missing:
        raise RuntimeError(f"legal_rules missing seed rules: {missing}")


def downgrade() -> None:
    pass
