#!/usr/bin/env python3
"""
NEUM LEX COUNSEL — Legal Rules Seeder v2.0
scripts/seed_rules.py

Standalone script to seed all 32 ILRMF v2.0 rules.
Safe to run multiple times — upserts by rule_id.

USAGE:
 python scripts/seed_rules.py
 python scripts/seed_rules.py --dry-run
 python scripts/seed_rules.py --verbose
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

try:
    from dotenv import load_dotenv
    load_dotenv(PROJECT_ROOT / ".env")
except ImportError:
    pass

import sqlalchemy as sa
from sqlalchemy.ext.asyncio import create_async_engine

# ═══════════════════════════════════════════════════════════════════════
# ILRMF v2.0 — 32 Rules
# ALL SECTION NUMBERS VERIFIED against Companies Act 1994 (Bangladesh)
# ═══════════════════════════════════════════════════════════════════════

ILRMF_RULES: List[Dict[str, Any]] = [
    # MODULE 0: INCORPORATION — 5 rules (Sec 9, 11, 90, 150)
    {"rule_id": "INC-001", "rule_name": "Certificate of Incorporation Not Obtained", "rule_type": "DEADLINE", "statutory_basis": "Section 9, Companies Act 1994 (Bangladesh)", "description": "Company commenced business without Certificate of Incorporation. Section 9: no business until certificate obtained. All pre-certificate contracts void.", "rule_condition": {"check_fn": "check_inc_001", "trigger": "certificate_obtained == False", "data_points": ["certificate_obtained"]}, "default_severity": "RED", "score_impact": 15, "revenue_tier": "STRUCTURED_REGULARIZATION", "is_black_override": False},
    {"rule_id": "INC-002", "rule_name": "Memorandum and Articles Not Filed", "rule_type": "DEADLINE", "statutory_basis": "Section 11, Companies Act 1994 (Bangladesh)", "description": "MoA and AoA not filed with RJSC. Section 11: constitutional documents required. Without filing, company has no valid constitution.", "rule_condition": {"check_fn": "check_inc_002", "trigger": "moa_filed == False OR aoa_filed == False", "data_points": ["moa_filed", "aoa_filed"]}, "default_severity": "BLACK", "score_impact": 25, "revenue_tier": "CORPORATE_RESCUE", "is_black_override": True},
    {"rule_id": "INC-003", "rule_name": "Minimum Directors Not Appointed", "rule_type": "THRESHOLD", "statutory_basis": "Section 90(2), Companies Act 1994 (Bangladesh)", "description": "Private company has fewer than 2 directors. Section 90(2): minimum 2 required. Cannot validly hold board meetings or pass resolutions.", "rule_condition": {"check_fn": "check_inc_003", "trigger": "company_type == PRIVATE_LIMITED AND current_director_count < 2", "data_points": ["company_type", "current_director_count"]}, "default_severity": "RED", "score_impact": 15, "revenue_tier": "STRUCTURED_REGULARIZATION", "is_black_override": False},
    {"rule_id": "INC-004", "rule_name": "Paid-Up Capital Exceeds Authorized Capital", "rule_type": "THRESHOLD", "statutory_basis": "Section 150, Companies Act 1994 (Bangladesh)", "description": "Paid-up capital exceeds authorized capital. Section 150: company cannot issue shares beyond authorized capital. All excess allotments void.", "rule_condition": {"check_fn": "check_inc_004", "trigger": "paid_up_capital_bdt > authorized_capital_bdt", "data_points": ["paid_up_capital_bdt", "authorized_capital_bdt"]}, "default_severity": "BLACK", "score_impact": 20, "revenue_tier": "CORPORATE_RESCUE", "is_black_override": True},
    {"rule_id": "INC-005", "rule_name": "Encashment Certificate Missing — Foreign Shareholding", "rule_type": "CONDITIONAL", "statutory_basis": "Section 150, Companies Act 1994; BIDA Foreign Investment Guidelines", "description": "Foreign shareholding detected but Encashment Certificate from AD bank not uploaded. Required under BIDA guidelines. CONDITIONAL: Only applies if has_foreign_shareholder == True.", "rule_condition": {"check_fn": "check_inc_005", "trigger": "has_foreign_shareholder == True AND encashment_certificate_uploaded == False", "data_points": ["has_foreign_shareholder", "encashment_certificate_uploaded"], "conditional": True}, "default_severity": "YELLOW", "score_impact": 8, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "INC-006", "rule_name": "Remittance Below Work Permit Threshold", "rule_type": "CONDITIONAL", "statutory_basis": "BIDA Foreign Investment Act 1980; BOI Guidelines", "description": "Foreign remittance below USD 50,000 threshold for work permit sponsorship. BIDA registration may be challenged. CONDITIONAL: Only applies if has_foreign_shareholder == True AND bida_registered == True.", "rule_condition": {"check_fn": "check_inc_006", "trigger": "has_foreign_shareholder == True AND remittance_amount_usd < 50000 AND bida_registered == True", "data_points": ["remittance_amount_usd", "bida_registered"], "conditional": True}, "default_severity": "YELLOW", "score_impact": 5, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},

    # MODULE 1: AUDIT — 4 rules (Sec 210, 151)
    {"rule_id": "AUD-001", "rule_name": "First Auditor Not Appointed Within 30 Days", "rule_type": "DEADLINE", "statutory_basis": "Section 210(1), Companies Act 1994 (Bangladesh)", "description": "First auditor not appointed by Board within 30 days of incorporation. Section 210(1): Board must appoint first auditor. Company cannot produce compliant accounts for first AGM.", "rule_condition": {"check_fn": "check_aud_001", "trigger": "first_auditor_appointed == False AND days_since_incorporation > 30", "data_points": ["first_auditor_appointed", "incorporation_date"]}, "default_severity": "YELLOW", "score_impact": 10, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "AUD-002", "rule_name": "Audit Not Completed Before AGM", "rule_type": "DEPENDENCY", "statutory_basis": "Section 151, Companies Act 1994 (Bangladesh)", "description": "Annual audit not completed before AGM. Section 151: directors must lay audited accounts at AGM. Presenting unaudited accounts renders adoption invalid and exposes directors to liability.", "rule_condition": {"check_fn": "check_aud_002", "trigger": "agm_held == True AND audit_complete == False", "data_points": ["agm_held", "audit_complete", "last_agm_date", "last_audit_signed_date"]}, "default_severity": "RED", "score_impact": 12, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "AUD-003", "rule_name": "AGM Held Without Completed Audit — BLACK OVERRIDE", "rule_type": "DEPENDENCY", "statutory_basis": "Sections 151, 210, Companies Act 1994 (Bangladesh)", "description": "AGM held but no audit completed. Fundamental statutory breach invalidating AGM, accounts, and all resolutions. Company may be liable for fraudulent AGM. BLACK OVERRIDE: forces score to BLACK band. Corporate Rescue mandatory.", "rule_condition": {"check_fn": "check_aud_003", "trigger": "agm_held == True AND audit_complete == False AND agm_held_without_audit == True", "data_points": ["agm_held", "audit_complete", "agm_held_without_audit"]}, "default_severity": "BLACK", "score_impact": 25, "revenue_tier": "CORPORATE_RESCUE", "is_black_override": True},
    {"rule_id": "AUD-004", "rule_name": "Auditor Not Reappointed at AGM", "rule_type": "DEPENDENCY", "statutory_basis": "Section 210(2), Companies Act 1994 (Bangladesh)", "description": "Auditor not reappointed at AGM. Section 210(2): mandatory at every AGM where accounts presented. Company without appointed auditor cannot file valid annual return.", "rule_condition": {"check_fn": "check_aud_004", "trigger": "agm_held == True AND auditor_reappointed_at_agm == False", "data_points": ["agm_held", "auditor_reappointed_at_agm"]}, "default_severity": "YELLOW", "score_impact": 5, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},

    # MODULE 2: AGM — 6 rules (Sec 81, 83, 85)
    {"rule_id": "AGM-001", "rule_name": "First AGM Default", "rule_type": "DEADLINE", "statutory_basis": "Section 81, Companies Act 1994 (Bangladesh)", "description": "First AGM not held within 18 months (548 days) of incorporation. Section 81 is mandatory; no waiver for private companies. Default counts from day after deadline.", "rule_condition": {"check_fn": "check_agm_001", "trigger": "first_agm_held == False AND days_since_incorporation > 548", "data_points": ["incorporation_date", "first_agm_held", "agm_count"]}, "default_severity": "RED", "score_impact": 20, "revenue_tier": "STRUCTURED_REGULARIZATION", "is_black_override": False},
    {"rule_id": "AGM-002", "rule_name": "Subsequent AGM Default", "rule_type": "DEADLINE", "statutory_basis": "Section 81, Companies Act 1994 (Bangladesh)", "description": "Subsequent AGM not held within 15 months of preceding AGM, or 6 months of FY end — whichever earlier. Section 81 makes no exception for size or dormancy.", "rule_condition": {"check_fn": "check_agm_002", "trigger": "days_since_last_agm > 456 OR days_since_fy_end > 182", "data_points": ["last_agm_date", "financial_year_end", "agm_count"]}, "default_severity": "RED", "score_impact": 20, "revenue_tier": "STRUCTURED_REGULARIZATION", "is_black_override": False},
    {"rule_id": "AGM-003", "rule_name": "AGM Notice Defective — Insufficient Days", "rule_type": "THRESHOLD", "statutory_basis": "Section 85, Companies Act 1994 (Bangladesh)", "description": "AGM notice sent with fewer than 21 clear days before meeting. Section 85 requires 21 clear days. 'Clear days' excludes day of service and day of meeting. Resolutions at improperly noticed AGM may be void.", "rule_condition": {"check_fn": "check_agm_003", "trigger": "notice_sent_date IS NOT NULL AND notice_days_before < 21", "data_points": ["notice_sent_date", "agm_date", "notice_days_before"]}, "default_severity": "YELLOW", "score_impact": 5, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "AGM-004", "rule_name": "AGM Notice Missing", "rule_type": "DEADLINE", "statutory_basis": "Section 85, Companies Act 1994 (Bangladesh)", "description": "No written AGM notice sent to members. Section 85 requires notice specifying date, time, place, and business. AGM without proper notice is a nullity — all resolutions void.", "rule_condition": {"check_fn": "check_agm_004", "trigger": "agm_held == True AND notice_sent_date IS NULL", "data_points": ["agm_held", "notice_sent_date"]}, "default_severity": "RED", "score_impact": 15, "revenue_tier": "STRUCTURED_REGULARIZATION", "is_black_override": False},
    {"rule_id": "AGM-005", "rule_name": "AGM Quorum Not Met", "rule_type": "THRESHOLD", "statutory_basis": "Section 83(12), Companies Act 1994 (Bangladesh)", "description": "AGM held but quorum not satisfied. Section 83(12): private companies need minimum 2 members present in person. Resolutions without quorum have no legal effect.", "rule_condition": {"check_fn": "check_agm_005", "trigger": "agm_held == True AND members_present < quorum_required", "data_points": ["agm_held", "members_present_at_agm", "quorum_required"]}, "default_severity": "RED", "score_impact": 15, "revenue_tier": "STRUCTURED_REGULARIZATION", "is_black_override": False},
    {"rule_id": "AGM-006", "rule_name": "AGM Minutes Not Prepared", "rule_type": "THRESHOLD", "statutory_basis": "Section 83, Companies Act 1994 (Bangladesh)", "description": "AGM held but minutes not prepared or signed by chairman. Section 83: minutes are prima facie evidence of proceedings. Without minutes, AGM validity can be challenged.", "rule_condition": {"check_fn": "check_agm_006", "trigger": "agm_held == True AND agm_minutes_prepared == False", "data_points": ["agm_held", "agm_minutes_prepared"]}, "default_severity": "YELLOW", "score_impact": 5, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},

    # MODULE 3: ANNUAL RETURNS — 4 rules (Sec 119, NOT 148)
    {"rule_id": "AR-001", "rule_name": "Annual Return Default — Single Year", "rule_type": "DEADLINE", "statutory_basis": "Section 119, Companies Act 1994 (Bangladesh)", "description": "Annual Return not filed within 30 days of AGM. Section 119 requires Form XII + Schedule X. Every officer in default is personally liable to fine for each day of continuing default.", "rule_condition": {"check_fn": "check_ar_001", "trigger": "annual_return_filed == False AND days_since_agm > 30 AND unfiled_returns_count == 1", "data_points": ["annual_return_filed", "last_agm_date", "unfiled_returns_count"]}, "default_severity": "YELLOW", "score_impact": 10, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "AR-002", "rule_name": "Annual Return 2-Year Backlog", "rule_type": "ESCALATION", "statutory_basis": "Sections 119 and 304, Companies Act 1994 (Bangladesh)", "description": "Annual returns unfiled for 2+ consecutive years. Multi-year default increases RJSC enforcement risk. RJSC may commence strike-off under Section 304. Directors face cumulative personal fines.", "rule_condition": {"check_fn": "check_ar_002", "trigger": "unfiled_returns_count >= 2", "data_points": ["unfiled_returns_count", "last_return_filed_year"]}, "default_severity": "RED", "score_impact": 20, "revenue_tier": "STRUCTURED_REGULARIZATION", "is_black_override": False},
    {"rule_id": "AR-003", "rule_name": "Annual Return 3-Year Backlog — Strike-Off Risk", "rule_type": "ESCALATION", "statutory_basis": "Sections 119 and 304, Companies Act 1994 (Bangladesh)", "description": "Annual returns unfiled for 3+ consecutive years. RJSC has legal basis and practice of initiating strike-off under Section 304. Struck-off company loses legal personality; contracts void, accounts frozen. Corporate Rescue mandatory.", "rule_condition": {"check_fn": "check_ar_003", "trigger": "unfiled_returns_count >= 3", "data_points": ["unfiled_returns_count", "last_return_filed_year"]}, "default_severity": "BLACK", "score_impact": 20, "revenue_tier": "CORPORATE_RESCUE", "is_black_override": False},
    {"rule_id": "AR-004", "rule_name": "Annual Return Filed But Incomplete", "rule_type": "THRESHOLD", "statutory_basis": "Section 119, Companies Act 1994 (Bangladesh)", "description": "Annual Return filed but missing required attachments: audited financial statements, directors list, members list, or secretary's certificate. Incomplete filing does not satisfy Section 119; company remains in default.", "rule_condition": {"check_fn": "check_ar_004", "trigger": "annual_return_filed == True AND annual_return_content_complete == False", "data_points": ["annual_return_filed", "annual_return_content_complete"]}, "default_severity": "YELLOW", "score_impact": 8, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},

    # MODULE 4: DIRECTORS — 4 rules (Sec 92, NOT 115), 14 days (NOT 30)
    {"rule_id": "DIR-001", "rule_name": "Director Appointment Not Filed Within 14 Days", "rule_type": "DEADLINE", "statutory_basis": "Section 92, Companies Act 1994 (Bangladesh)", "description": "Director appointment not filed via Form XII within 14 days. Section 92 requires 14-day filing (NOT 30 days). Until filed, third parties cannot verify director authority, invalidating contracts and resolutions.", "rule_condition": {"check_fn": "check_dir_001", "trigger": "director_change_type == APPOINTMENT AND appointment_delay_days > 14", "data_points": ["director_changes", "appointment_date", "appointment_delay_days"]}, "default_severity": "YELLOW", "score_impact": 10, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "DIR-002", "rule_name": "Director Departure Not Filed Within 14 Days", "rule_type": "DEADLINE", "statutory_basis": "Section 92, Companies Act 1994 (Bangladesh)", "description": "Director resignation/removal/death not filed via Form XII within 14 days. Section 92 requires 14-day filing. Until filed, departed director remains on public record as active, creating liability for post-departure obligations.", "rule_condition": {"check_fn": "check_dir_002", "trigger": "director_change_type == DEPARTURE AND departure_delay_days > 14", "data_points": ["director_changes", "departure_date", "departure_delay_days"]}, "default_severity": "YELLOW", "score_impact": 10, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "DIR-003", "rule_name": "Major Director Filing Irregularity — Over 1 Year", "rule_type": "ESCALATION", "statutory_basis": "Section 92, Companies Act 1994 (Bangladesh)", "description": "Director change unfiled for over 1 year. Continuing offence under Section 92. Prolonged non-filing creates compounding personal liability. Each day of default adds to statutory fine. Board resolutions may be challenged.", "rule_condition": {"check_fn": "check_dir_003", "trigger": "director_filing_delay_days > 365", "data_points": ["director_changes", "appointment_delay_days", "departure_delay_days"]}, "default_severity": "RED", "score_impact": 15, "revenue_tier": "STRUCTURED_REGULARIZATION", "is_black_override": False},
    {"rule_id": "DIR-004", "rule_name": "Departed Director Still Active on RJSC Register", "rule_type": "DEPENDENCY", "statutory_basis": "Section 92, Companies Act 1994 (Bangladesh)", "description": "Departed director still recorded as active on RJSC register because Form XII not filed. Departed director continues to bear personal liability for obligations while on record. Enables fraudulent authority claims.", "rule_condition": {"check_fn": "check_dir_004", "trigger": "departed_still_liable == True", "data_points": ["director_changes", "departed_still_liable"]}, "default_severity": "RED", "score_impact": 10, "revenue_tier": "STRUCTURED_REGULARIZATION", "is_black_override": False},

    # MODULE 5: SHAREHOLDING — 3 rules (Sec 50, 46, 52)
    {"rule_id": "SH-001", "rule_name": "Share Allotment Not Filed — Form XV", "rule_type": "DEADLINE", "statutory_basis": "Section 50, Companies Act 1994 (Bangladesh)", "description": "Share allotment not filed via Form XV within 30 days. Section 50 requires return of allotment. Failure means allotment not reflected in RJSC register, creating uncertainty about issued capital.", "rule_condition": {"check_fn": "check_sh_001", "trigger": "last_allotment_date IS NOT NULL AND form_xv_filed == False AND days_since_allotment > 30", "data_points": ["last_allotment_date", "form_xv_filed"]}, "default_severity": "YELLOW", "score_impact": 8, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "SH-002", "rule_name": "Share Certificates Not Issued Within 60 Days", "rule_type": "DEADLINE", "statutory_basis": "Section 46, Companies Act 1994 (Bangladesh)", "description": "Share certificates not issued within 60 days of allotment. Section 46 requires certificates within 2 months. Non-issuance means no documentary evidence of ownership, obstructing transfers and dividends.", "rule_condition": {"check_fn": "check_sh_002", "trigger": "share_certificates_issued == False AND last_allotment_date IS NOT NULL AND days_since_allotment > 60", "data_points": ["share_certificates_issued", "last_allotment_date"]}, "default_severity": "YELLOW", "score_impact": 5, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "SH-003", "rule_name": "Capital Increase Not Filed — Form IV", "rule_type": "DEADLINE", "statutory_basis": "Section 52, Companies Act 1994 (Bangladesh)", "description": "Capital increase not filed via Form IV within 30 days of special resolution. Section 52 requires notice of increase. Unrecorded increases cause RJSC records to differ from actual capital.", "rule_condition": {"check_fn": "check_sh_003", "trigger": "capital_increase_date IS NOT NULL AND form_iv_filed == False AND days_since_capital_increase > 30", "data_points": ["capital_increase_date", "form_iv_filed"]}, "default_severity": "YELLOW", "score_impact": 8, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},

    # MODULE 6: SHARE TRANSFERS — 6 rules (Sec 108, 47, 34)
    {"rule_id": "TR-001", "rule_name": "No Share Transfer Instrument — Form 117", "rule_type": "THRESHOLD", "statutory_basis": "Section 108, Companies Act 1994 (Bangladesh)", "description": "Share transfer without Form 117 instrument. Section 108 requires proper instrument of transfer, duly stamped, executed by both parties. Missing instrument renders transfer void and unregistrable.", "rule_condition": {"check_fn": "check_tr_001", "trigger": "has_instrument == False", "data_points": ["share_transfers", "has_instrument"]}, "default_severity": "YELLOW", "score_impact": 5, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "TR-002", "rule_name": "Stamp Duty Not Paid on Share Transfer", "rule_type": "THRESHOLD", "statutory_basis": "Stamp Act 1899 (Bangladesh), Schedule I, Item 62", "description": "Stamp duty not paid on share transfer. Stamp Act 1899 requires ad valorem duty. Unstamped instrument inadmissible in court and cannot be registered. Transferee's ownership unenforceable until duty paid.", "rule_condition": {"check_fn": "check_tr_002", "trigger": "has_instrument == True AND stamp_paid == False", "data_points": ["share_transfers", "stamp_paid"]}, "default_severity": "YELLOW", "score_impact": 5, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "TR-003", "rule_name": "No Board Approval for Share Transfer", "rule_type": "THRESHOLD", "statutory_basis": "Section 47, Companies Act 1994 (Bangladesh); Articles of Association", "description": "Share transfer without board approval where AoA restricts transfer. Section 47 + AoA: board approval required. Transfer in breach is void; transferee has no legal title. Register cannot be validly updated.", "rule_condition": {"check_fn": "check_tr_003", "trigger": "board_approved == False AND aoa_transfer_restriction == True", "data_points": ["share_transfers", "board_approved", "aoa_transfer_restriction"]}, "default_severity": "YELLOW", "score_impact": 8, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "TR-004", "rule_name": "Register of Members Not Updated After Transfer", "rule_type": "DEADLINE", "statutory_basis": "Section 34, Companies Act 1994 (Bangladesh)", "description": "Register of Members not updated within 2 months of transfer lodgement. Section 34 requires register update. Until updated, transferee is not recognized member and cannot exercise rights.", "rule_condition": {"check_fn": "check_tr_004", "trigger": "register_updated == False AND transfer_date IS NOT NULL", "data_points": ["share_transfers", "register_updated", "transfer_date"]}, "default_severity": "YELLOW", "score_impact": 5, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "TR-005", "rule_name": "Share Transfer Violates AoA Restriction — BLACK OVERRIDE", "rule_type": "THRESHOLD", "statutory_basis": "Section 47, Companies Act 1994 (Bangladesh); Articles of Association", "description": "Transfer executed in violation of AoA restriction — pre-emption rights not offered, prohibited transferee, or board approval refused. Transfer is void ab initio. Transferee has no legal title. Rectification requires court order or unanimous ratification. BLACK OVERRIDE: forces score to BLACK band. Corporate Rescue mandatory.", "rule_condition": {"check_fn": "check_tr_005", "trigger": "aoa_violated == True", "data_points": ["share_transfers", "aoa_violated"]}, "default_severity": "BLACK", "score_impact": 15, "revenue_tier": "CORPORATE_RESCUE", "is_black_override": True},
    {"rule_id": "TR-006", "rule_name": "Composite Irregular Transfer", "rule_type": "CASCADE", "statutory_basis": "Sections 34, 47, 108, Companies Act 1994 (Bangladesh)", "description": "Transfer has 2+ concurrent deficiencies from TR-001 to TR-005. Composite irregularity compounds legal risk. Each deficiency may independently void transfer. Together they indicate systemic share administration failure requiring structured remediation.", "rule_condition": {"check_fn": "check_tr_006", "trigger": "is_irregular == True AND irregularity_count >= 2", "data_points": ["share_transfers", "is_irregular"]}, "default_severity": "RED", "score_impact": 10, "revenue_tier": "STRUCTURED_REGULARIZATION", "is_black_override": False},

    # MODULE 7: STATUTORY REGISTERS — 3 rules (Sec 34, 83, 87, 90)
    {"rule_id": "REG-001", "rule_name": "Statutory Registers Incomplete", "rule_type": "THRESHOLD", "statutory_basis": "Sections 34, 83, 87, 90, Companies Act 1994 (Bangladesh)", "description": "One or more of 7 mandatory statutory registers not maintained at registered office. Required: Members (Sec 34), Directors (Sec 90), Charges (Sec 87), Transfers (Sec 108), Debentures (Sec 90), AGM Minutes (Sec 83), Board Minutes (Sec 90). Failure is criminal offence; officers personally liable.", "rule_condition": {"check_fn": "check_reg_001", "trigger": "len(maintained_registers) < 7", "data_points": ["maintained_registers"]}, "default_severity": "YELLOW", "score_impact": 5, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "REG-002", "rule_name": "Core Statutory Registers Missing", "rule_type": "THRESHOLD", "statutory_basis": "Sections 34, 83, 87, 90, Companies Act 1994 (Bangladesh)", "description": "Core registers missing: Members (Sec 34), Directors (Sec 90), Charges (Sec 87), or AGM Minutes (Sec 83). These are minimum required for basic corporate governance. Absence indicates fundamental governance failure.", "rule_condition": {"check_fn": "check_reg_002", "trigger": "members_register_missing == True OR directors_register_missing == True OR charges_register_missing == True OR minutes_agm_missing == True", "data_points": ["register_of_members_maintained", "register_of_directors_maintained", "register_of_charges_maintained", "minutes_book_agm_maintained"]}, "default_severity": "RED", "score_impact": 10, "revenue_tier": "STRUCTURED_REGULARIZATION", "is_black_override": False},
    {"rule_id": "REG-003", "rule_name": "Registers Not Kept at Registered Office", "rule_type": "THRESHOLD", "statutory_basis": "Section 34(2), Companies Act 1994 (Bangladesh)", "description": "Statutory registers not at registered office. Section 34(2): registers must be at registered office unless RJSC notified of alternative location. Alternative must be in Bangladesh and Board-approved. Registers open to inspection during business hours.", "rule_condition": {"check_fn": "check_reg_003", "trigger": "register_location != registered_office AND alternative_location_notified == False", "data_points": ["register_location", "alternative_location_notified"]}, "default_severity": "YELLOW", "score_impact": 3, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},

    # MODULE 8: REGISTERED OFFICE — 1 rule (Sec 81, Form VI, 28 days)
    {"rule_id": "OFF-001", "rule_name": "Change of Registered Office Not Filed Within 28 Days", "rule_type": "DEADLINE", "statutory_basis": "Section 81, Companies Act 1994 (Bangladesh)", "description": "Office change not filed via Form VI within 28 days. Section 81 requires 28-day filing (NOT 30 days). Until filed, old address remains legal registered office. Statutory notices served there are valid.", "rule_condition": {"check_fn": "check_off_001", "trigger": "registered_office_change_date IS NOT NULL AND form_vi_filed == False AND days_since_office_change > 28", "data_points": ["registered_office_change_date", "form_vi_filed"]}, "default_severity": "YELLOW", "score_impact": 3, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},

    # MODULE 9: CAPITAL & CHARGES — 4 rules (Sec 54, 87, 52)
    {"rule_id": "CAP-001", "rule_name": "Capital Alteration Without Proper Resolution", "rule_type": "CASCADE", "statutory_basis": "Section 54, Companies Act 1994 (Bangladesh)", "description": "Capital alteration without required board/special resolution, or forms not filed. Section 54 governs capital increase procedure. Unrecorded changes cause RJSC register to differ from actual capital, creating legal uncertainty.", "rule_condition": {"check_fn": "check_cap_001", "trigger": "capital_increase_date IS NOT NULL AND capital_increase_resolution == False", "data_points": ["capital_increase_date", "capital_increase_resolution"]}, "default_severity": "YELLOW", "score_impact": 5, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "CAP-002", "rule_name": "Charge Not Registered With RJSC Within 30 Days", "rule_type": "DEADLINE", "statutory_basis": "Section 87, Companies Act 1994 (Bangladesh)", "description": "Charge created but not registered via Form VIII within 30 days. Section 87: unregistered charge is void against liquidator and creditors. Lender loses security interest, becomes unsecured creditor. Officers personally liable.", "rule_condition": {"check_fn": "check_cap_002", "trigger": "charge_creation_date IS NOT NULL AND form_viii_filed == False AND days_since_charge_creation > 30", "data_points": ["charge_creation_date", "form_viii_filed"]}, "default_severity": "YELLOW", "score_impact": 5, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "CAP-003", "rule_name": "Charge Satisfaction Not Filed", "rule_type": "DEADLINE", "statutory_basis": "Section 87(2), Companies Act 1994 (Bangladesh)", "description": "Charge paid off but Form XXVIII (Satisfaction) not filed. Section 87(2): file within 30 days of payoff. Until filed, charge remains on register, obstructing future borrowing and creating false security interests.", "rule_condition": {"check_fn": "check_cap_003", "trigger": "charge_paid_off == True AND form_xxviii_filed == False AND days_since_payoff > 30", "data_points": ["charge_paid_off", "form_xxviii_filed"]}, "default_severity": "YELLOW", "score_impact": 3, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},
    {"rule_id": "CAP-004", "rule_name": "Special Resolution Not Filed With RJSC", "rule_type": "DEADLINE", "statutory_basis": "Section 87, Companies Act 1994 (Bangladesh)", "description": "Special resolution passed but not filed within 30 days. Section 87: every special resolution must be filed. Unfiled resolution not binding on company or enforceable against third parties. Includes capital increase, MoA/AoA alteration, voluntary winding up.", "rule_condition": {"check_fn": "check_cap_004", "trigger": "special_resolution_date IS NOT NULL AND form_viii_filed == False AND days_since_resolution > 30", "data_points": ["special_resolution_date", "form_viii_filed"]}, "default_severity": "YELLOW", "score_impact": 8, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},

    # MODULE 10: TAX — 2 rules (Income Tax Act 2023, VAT Act 2012)
    {"rule_id": "TAX-001", "rule_name": "Tax Identification Number (TIN) Not Obtained", "rule_type": "THRESHOLD", "statutory_basis": "Income Tax Act 2023 (Bangladesh)", "description": "No TIN from NBR. Income Tax Act 2023: TIN mandatory for all companies. Without TIN: cannot file returns, open bank accounts, obtain import licenses, participate in tenders, or claim exemptions. Directors may face liability for trading without TIN.", "rule_condition": {"check_fn": "check_tax_001", "trigger": "tin_obtained == False", "data_points": ["tin_obtained", "tin_number"]}, "default_severity": "RED", "score_impact": 10, "revenue_tier": "STRUCTURED_REGULARIZATION", "is_black_override": False},
    {"rule_id": "TAX-002", "rule_name": "VAT Registration Required But Not Obtained", "rule_type": "CONDITIONAL", "statutory_basis": "Value Added Tax Act 2012 (Bangladesh)", "description": "Company exceeds VAT threshold but not registered. VAT Act 2012: registration required above turnover threshold (Tk 30 lakh goods, Tk 15 lakh services). Without VAT: cannot issue tax invoices, claim input credits, or legally supply taxable goods/services. CONDITIONAL: Only applies if estimated turnover exceeds threshold.", "rule_condition": {"check_fn": "check_tax_002", "trigger": "vat_registered == False AND estimated_turnover_bdt > 3000000", "data_points": ["vat_registered", "estimated_turnover_bdt"], "conditional": True}, "default_severity": "YELLOW", "score_impact": 5, "revenue_tier": "COMPLIANCE_PACKAGE", "is_black_override": False},

    # MODULE 11: ESCALATION — 3 rules (Sec 304, NOT 396)
    {"rule_id": "ESC-001", "rule_name": "Strike-Off Risk Elevated", "rule_type": "ESCALATION", "statutory_basis": "Section 304, Companies Act 1994 (Bangladesh)", "description": "Compliance profile shows RJSC strike-off criteria under Section 304: multi-year missed filings, no recent trading, or RED flags across 3+ modules. Section 304 permits strike-off for non-filing or non-trading. Structured Regularization required immediately.", "rule_condition": {"check_fn": "check_esc_001", "trigger": "unfiled_returns_count >= 2 OR (active_red_flags >= 3 AND active_yellow_flags >= 4)", "data_points": ["unfiled_returns_count", "active_red_flags", "active_yellow_flags"]}, "default_severity": "RED", "score_impact": 15, "revenue_tier": "STRUCTURED_REGULARIZATION", "is_black_override": False},
    {"rule_id": "ESC-002", "rule_name": "Strike-Off Imminent — BLACK OVERRIDE", "rule_type": "ESCALATION", "statutory_basis": "Section 304, Companies Act 1994 (Bangladesh)", "description": "Immediate RJSC strike-off risk. Criteria: 3+ years non-filing, strike-off notice received, or on published strike-off list. Once struck off: company ceases to exist, contracts void, accounts frozen. Restoration requires court proceedings under Section 305. Corporate Rescue mandatory. BLACK OVERRIDE: forces score to BLACK band.", "rule_condition": {"check_fn": "check_esc_002", "trigger": "unfiled_returns_count >= 3 OR rjsc_strike_off_notice == True OR on_rjsc_strike_off_list == True", "data_points": ["unfiled_returns_count", "rjsc_strike_off_notice", "on_rjsc_strike_off_list"]}, "default_severity": "BLACK", "score_impact": 25, "revenue_tier": "CORPORATE_RESCUE", "is_black_override": True},
    {"rule_id": "ESC-003", "rule_name": "Corporate Rescue Mandatory — Systemic Failure", "rule_type": "ESCALATION", "statutory_basis": "Section 304, Companies Act 1994 (Bangladesh)", "description": "Score below BLACK threshold (<=29) due to systemic multi-module failures: BLACK overrides from AUD-003, TR-005, ESC-002, or RED/YELLOW across 4+ modules. Legal status, contractual capacity, and director exposure all critical. 10-step Corporate Rescue mandatory within 30 days. BLACK OVERRIDE: maintains BLACK until rescue verified.", "rule_condition": {"check_fn": "check_esc_003", "trigger": "pre_override_score <= 29 OR has_black_override == True", "data_points": ["pre_override_score", "has_black_override", "active_red_flags", "active_black_flags"]}, "default_severity": "BLACK", "score_impact": 25, "revenue_tier": "CORPORATE_RESCUE", "is_black_override": True},
]

EXPECTED_RULE_COUNT = 32


def get_database_url() -> str:
    url = os.environ.get("DATABASE_URL", "")
    if not url:
        raise RuntimeError("DATABASE_URL not set. Export DATABASE_URL=postgresql+asyncpg://...")
    if url.startswith("postgresql://"):
        url = url.replace("postgresql://", "postgresql+asyncpg://", 1)
    if url.startswith("postgres://"):
        url = url.replace("postgres://", "postgresql+asyncpg://", 1)
    return url


async def seed_rules(dry_run: bool = False, verbose: bool = False) -> int:
    print(f"\n{'='*60}")
    print(f" NEUM LEX COUNSEL — Legal Rules Seeder v2.0")
    print(f" ILRMF v2.0 — {EXPECTED_RULE_COUNT} rules")
    print(f" Mode: {'DRY RUN' if dry_run else 'LIVE'}")
    print(f"{'='*60}\n")

    valid_types = {"AGM", "AUDIT", "RETURN", "DIRECTOR", "TRANSFER", "REGISTER",
                   "ESCALATION", "CASCADE", "DEADLINE", "DEPENDENCY", "THRESHOLD", "CONDITIONAL"}
    valid_sev = {"GREEN", "YELLOW", "RED", "BLACK"}
    valid_tier = {"COMPLIANCE_PACKAGE", "STRUCTURED_REGULARIZATION", "CORPORATE_RESCUE"}

    print("Validating...")
    seen = set()
    for rule in ILRMF_RULES:
        issues = []
        if rule["rule_id"] in seen:
            issues.append("duplicate")
        seen.add(rule["rule_id"])
        if rule["rule_type"] not in valid_types:
            issues.append(f"bad type: {rule['rule_type']}")
        if rule["default_severity"] not in valid_sev:
            issues.append(f"bad severity: {rule['default_severity']}")
        if rule["revenue_tier"] not in valid_tier:
            issues.append(f"bad tier: {rule['revenue_tier']}")
        if rule["is_black_override"] and rule["default_severity"] != "BLACK":
            issues.append("override=True but severity!=BLACK")
        if issues:
            raise ValueError(f"{rule['rule_id']}: {', '.join(issues)}")
        if verbose:
            print(f"  {rule['rule_id']:10s} {rule['default_severity']:7s} {rule['score_impact']:2d}pts {rule['rule_name'][:50]}")

    if len(ILRMF_RULES) != EXPECTED_RULE_COUNT:
        raise ValueError(f"Expected {EXPECTED_RULE_COUNT}, got {len(ILRMF_RULES)}")
    print(f"\n  All {len(ILRMF_RULES)} rules valid\n")

    if dry_run:
        from collections import Counter
        mods = Counter(r["rule_id"].split("-")[0] for r in ILRMF_RULES)
        print("Module summary:")
        for m, cnt in sorted(mods.items()):
            print(f"  {m:6s}: {cnt} rules")
        blacks = [r["rule_id"] for r in ILRMF_RULES if r["is_black_override"]]
        print(f"\nBLACK overrides ({len(blacks)}): {', '.join(blacks)}")
        print(f"Max deduction: {sum(r['score_impact'] for r in ILRMF_RULES)} pts")
        print("\nDry run complete.")
        return 0

    db_url = get_database_url()
    engine = create_async_engine(db_url, echo=False)

    async with engine.begin() as conn:
        inserted = updated = 0
        now = datetime.now(timezone.utc)

