#!/usr/bin/env python3
"""Generate alembic/versions/0026_reconcile_rule_law.py from scripts/seed_rules.py.

Run from repo root AFTER scripts/seed_rules.py holds the final canonical values:
    python tools/gen_rule_sync_migration.py [--force]

The output is a frozen snapshot: values are embedded in the migration, not imported,
so later edits to seed_rules.py never change what this migration does.
It UPDATEs existing rows by rule_id only (no inserts, no deletes) and aborts the
migration if any seed rule is missing from legal_rules. Downgrade is a no-op.
"""
import pprint
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from scripts.seed_rules import ILRMF_RULES  # noqa: E402

REVISION = "0026_reconcile_rule_law"
DOWN = "0025_harden_access_table_rls"
VERSIONS = ROOT / "alembic" / "versions"
OUT = VERSIONS / f"{REVISION}.py"
force = "--force" in sys.argv

# refuse if the DOWN revision is not the single current head
revs, downs = set(), set()
for p in VERSIONS.glob("*.py"):
    txt = p.read_text(encoding="utf-8")
    m = re.search(r'^revision[^=\n]*=\s*["\']([^"\']+)["\']', txt, re.M)
    if m:
        revs.add(m.group(1))
    d = re.search(r'^down_revision[^=\n]*=\s*(None|["\'][^"\']+["\'])', txt, re.M)
    if d and d.group(1) != "None":
        downs.add(d.group(1).strip("\"'"))
heads = revs - downs - {REVISION}
if heads != {DOWN} and not force:
    sys.exit(f"ABORT: current alembic heads {sorted(heads)} != expected {{'{DOWN}'}} (use --force to override)")
if OUT.exists() and not force:
    sys.exit(f"ABORT: {OUT} exists (use --force to overwrite)")

rows = [
    (
        r["rule_id"], r["rule_name"], r["rule_type"], r["statutory_basis"], r["description"],
        json.dumps(r["rule_condition"], sort_keys=True),
        r["default_severity"], int(r["score_impact"]), r["revenue_tier"], bool(r["is_black_override"]),
    )
    for r in ILRMF_RULES
]

TEMPLATE = '''"""Reconcile legal_rules to the canonical seed (citations, severity, score, black override)

Revision:  __REV__
Previous:  __DOWN__

Generated by tools/gen_rule_sync_migration.py from scripts/seed_rules.py.
Frozen snapshot of __N__ rules. Idempotent UPDATE by rule_id; never inserts or deletes.
Aborts if any rule is missing from legal_rules. Downgrade is a no-op (previous
values are not retained).
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "__REV__"
down_revision: Union[str, None] = "__DOWN__"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (rule_id, rule_name, rule_type, statutory_basis, description, rule_condition_json,
#  default_severity, score_impact, revenue_tier, is_black_override)
RULES = __ROWS__


def upgrade() -> None:
    conn = op.get_bind()
    missing = []
    for (rule_id, name, rtype, basis, descr, cond, sev, score, tier, black) in RULES:
        res = conn.execute(sa.text("""
            UPDATE legal_rules SET
                rule_name         = :name,
                rule_type         = CAST(:rtype AS rule_type),
                statutory_basis   = :basis,
                description       = :descr,
                rule_condition    = CAST(:cond AS jsonb),
                default_severity  = CAST(:sev AS severity_level),
                score_impact      = :score,
                revenue_tier      = CAST(:tier AS revenue_tier),
                is_black_override = :black,
                is_active         = TRUE,
                updated_at        = NOW()
            WHERE rule_id = :rid
        """), {
            "rid": rule_id, "name": name, "rtype": rtype, "basis": basis, "descr": descr,
            "cond": cond, "sev": sev, "score": score, "tier": tier, "black": black,
        })
        if res.rowcount != 1:
            missing.append(rule_id)
    if missing:
        raise RuntimeError(f"legal_rules missing seed rules: {missing}")


def downgrade() -> None:
    pass
'''

body = (
    TEMPLATE.replace("__REV__", REVISION)
    .replace("__DOWN__", DOWN)
    .replace("__N__", str(len(rows)))
    .replace("__ROWS__", pprint.pformat(rows, width=110))
)
OUT.write_text(body, encoding="utf-8")
print(f"wrote {OUT.relative_to(ROOT)}  ({len(rows)} rules)")
